import { githubPath } from "./githubCurriculum";
import { difficultyGuidance } from "./curriculumDifficulty";
import { buildLessonQuiz, type LessonQuizQuestion } from "./curriculumQuiz";

export { difficultyGuidance } from "./curriculumDifficulty";

export type LanguageId = "html" | "css" | "javascript" | "python" | "github";

export type Keyword = { term: string; meaning: string };
export type LessonChallenge = { prompt: string; starter: string; expected: string[]; hint: string; xp: number; kind?: "build" | "debug" | "predict" | "timed"; prediction?: { prompt: string; answer: string } };
export type PathLesson = {
  id: string;
  order: number;
  title: string;
  duration: string;
  summary: string;
  keywords: Keyword[];
  code: string;
  challenge: LessonChallenge;
  checkpoint: { question: string; choices: string[]; answer: number; explanation: string };
  quiz?: LessonQuizQuestion[];
};
export type LanguagePath = { id: LanguageId; label: string; accent: string; pale: string; source: string; sourceLabel: string; description: string; project: string; lessons: PathLesson[] };

const htmlLessons: PathLesson[] = [
  { id: "html-document", order: 1, title: "HTML баримтын үндэс", duration: "20 мин", summary: "Browser хэрхэн HTML файлыг уншдагийг ойлгож, head ба body-ийн үүргийг ялгана.", keywords: [{ term: "<!doctype html>", meaning: "Баримтыг HTML5 гэж browser-д зарлана." }, { term: "<html lang>", meaning: "Баримтын үндсэн element ба хэлний код." }, { term: "<head>", meaning: "Metadata, title, холбоосуудын хэсэг." }, { term: "<body>", meaning: "Хэрэглэгчид харагдах агуулгын хэсэг." }, { term: "<meta charset>", meaning: "Тэмдэгтийн кодчиллыг UTF-8 болгоно." }, { term: "<title>", meaning: "Browser tab дээр харагдах гарчиг." }], code: "<!doctype html>\n<html lang=\"mn\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <title>Миний анхны хуудас</title>\n  </head>\n  <body>\n    <p>Сайн байна уу.</p>\n  </body>\n</html>", challenge: { prompt: "Монгол хэлтэй HTML5 баримт үүсгээд browser tab-ийн гарчгийг `CodeCraft HTML` болго.", starter: "<!doctype html>\n<html>\n  <head>\n  </head>\n  <body>\n  </body>\n</html>", expected: ["lang=\"mn\"", "<meta charset=\"UTF-8\"", "<title>CodeCraft HTML</title>"], hint: "`lang` attribute нь `<html>` дээр, `meta` болон `title` нь `<head>` дотор байрлана.", xp: 20 }, checkpoint: { question: "Хэрэглэгчийн дэлгэцэд харагдах агуулга хаана ордог вэ?", choices: ["<head>", "<body>", "<title>"], answer: 1, explanation: "`body` нь page-ийн харагдах агуулгыг агуулна." } },
  { id: "html-semantic-text", order: 2, title: "Гарчиг ба semantic бүтэц", duration: "30 мин", summary: "Уншигдахуйц болон accessibility-д ээлтэй контентын бүтцийг semantic element-ээр зохион байгуулна.", keywords: [{ term: "<h1>–<h6>", meaning: "Гарчгийн шатлал." }, { term: "<p>", meaning: "Догол мөр." }, { term: "<header>", meaning: "Хуудас эсвэл section-ийн оршил." }, { term: "<nav>", meaning: "Навигацийн холбоосууд." }, { term: "<main>", meaning: "Давтагдашгүй гол агуулга." }, { term: "<section>", meaning: "Гарчигтай холбоотой агуулгын бүлэг." }, { term: "<article>", meaning: "Бие даан түгээгдэж болох контент." }, { term: "<footer>", meaning: "Төгсгөлийн мэдээлэл." }], code: "<header>\n  <h1>CodeCraft тэмдэглэл</h1>\n  <nav><a href=\"#lessons\">Хичээл</a></nav>\n</header>\n<main>\n  <section id=\"lessons\">\n    <h2>HTML-ийн эхлэл</h2>\n    <article><p>Semantic structure нь утгыг илэрхийлдэг.</p></article>\n  </section>\n</main>\n<footer>2026</footer>", challenge: { prompt: "`main` дотор `section` үүсгэж, түүнд `h2` ба `article` байрлуул. Article дотор нэг paragraph бич.", starter: "<main>\n  \n</main>", expected: ["<section", "<h2", "<article", "<p>"], hint: "Том агуулгыг section, бие даасан бичвэрийг article-аар ялга.", xp: 25 }, checkpoint: { question: "Хуудасны цорын ганц үндсэн агуулгыг аль element илэрхийлдэг вэ?", choices: ["<main>", "<div>", "<span>"], answer: 0, explanation: "`main` нь document-ийн гол, давтагдашгүй агуулгыг тэмдэглэнэ." } },
  { id: "html-links-media", order: 3, title: "Холбоос, зураг, media", duration: "28 мин", summary: "Хэрэглэгчийг чиглүүлэх холбоос болон утгатай media контент оруулна.", keywords: [{ term: "<a href>", meaning: "Холбоос үүсгэх." }, { term: "target=\"_blank\"", meaning: "Холбоосыг шинэ tab-д нээх." }, { term: "rel=\"noreferrer\"", meaning: "Гадаад tab нээхэд аюулгүй байдлын нэмэлт attribute." }, { term: "<img src alt>", meaning: "Зураг ба текстэн тайлбар." }, { term: "<figure>", meaning: "Зураг/diagram шиг бие даасан media." }, { term: "<figcaption>", meaning: "Figure-ийн тайлбар." }, { term: "<audio>, <video>", meaning: "Media тоглуулах element." }], code: "<figure>\n  <img src=\"lesson-map.png\" alt=\"HTML хичээлийн маршрут\" />\n  <figcaption>Эхний долоон хоногийн зам.</figcaption>\n</figure>\n<a href=\"https://developer.mozilla.org\" target=\"_blank\" rel=\"noreferrer\">MDN нээх</a>", challenge: { prompt: "`figure` дотор alt-той зураг, figcaption нэм. Дараа нь MDN рүү шинэ tab-д нээгдэх аюулгүй холбоос бич.", starter: "<figure>\n  \n</figure>\n\n<a>MDN</a>", expected: ["<img", "alt=", "<figcaption>", "href=", "target=\"_blank\""], hint: "Зураг бүр утгатай `alt`-тай байх ёстой.", xp: 25 }, checkpoint: { question: "Зургийн утгыг screen reader-д дамжуулах гол attribute аль нь вэ?", choices: ["src", "alt", "width"], answer: 1, explanation: "`alt` нь зургийн текстэн хувилбар юм." } },
  { id: "html-lists-tables", order: 4, title: "Жагсаалт ба хүснэгт", duration: "25 мин", summary: "Дараалалтай/дараалалгүй өгөгдөл болон мөр-багана бүтэцтэй мэдээллийг зөв тэмдэглэнэ.", keywords: [{ term: "<ul>, <ol>", meaning: "Дараалалгүй, дараалалтай жагсаалт." }, { term: "<li>", meaning: "Жагсаалтын нэг item." }, { term: "<dl>, <dt>, <dd>", meaning: "Нэр томьёо, тайлбарын жагсаалт." }, { term: "<table>", meaning: "Хүснэгтийн контейнер." }, { term: "<thead>, <tbody>", meaning: "Хүснэгтийн толгой, үндсэн бие." }, { term: "<tr>, <th>, <td>", meaning: "Мөр, толгой нүд, өгөгдлийн нүд." }, { term: "scope", meaning: "Table header ямар нүдэнд хамаарахыг заана." }], code: "<table>\n  <thead><tr><th scope=\"col\">Хэл</th><th scope=\"col\">Хичээл</th></tr></thead>\n  <tbody><tr><td>HTML</td><td>6</td></tr></tbody>\n</table>", challenge: { prompt: "HTML ба CSS гэсэн хоёр мөртэй, Хэл ба Хичээл гэсэн хоёр баганатай accessible хүснэгт үүсгэ.", starter: "<table>\n  \n</table>", expected: ["<thead>", "<tbody>", "<th", "scope=\"col\"", "<td>"], hint: "Column header дээр `scope=\"col\"` нэмэхийг санаарай.", xp: 25 }, checkpoint: { question: "Хүснэгтийн толгой нүдийг аль tag илэрхийлдэг вэ?", choices: ["<td>", "<th>", "<tr>"], answer: 1, explanation: "`th` нь хүснэгтийн header cell-д ашиглагдана." } },
  { id: "html-forms", order: 5, title: "Form ба хэрэглэгчийн input", duration: "35 мин", summary: "Мэдээлэл цуглуулах form-ыг label, type, validation attribute-тайгаар бүтээнэ.", keywords: [{ term: "<form>", meaning: "Input-уудыг нэг submit урсгалд багцална." }, { term: "<label for>", meaning: "Input-ын нэр ба accessibility холболт." }, { term: "<input type>", meaning: "text, email, password, checkbox зэрэг input төрөл." }, { term: "<textarea>", meaning: "Олон мөрт текст." }, { term: "<select>, <option>", meaning: "Сонголтын жагсаалт." }, { term: "required", meaning: "Заавал бөглөх validation." }, { term: "<button type=\"submit\">", meaning: "Form submit хийх товч." }], code: "<form>\n  <label for=\"email\">Имэйл</label>\n  <input id=\"email\" name=\"email\" type=\"email\" required />\n  <label for=\"note\">Тайлбар</label>\n  <textarea id=\"note\" name=\"note\"></textarea>\n  <button type=\"submit\">Илгээх</button>\n</form>", challenge: { prompt: "Email болон тайлбар авдаг form хий. Label нь input/textarea-тай `for` ба `id`-аар холбогдсон байх ёстой.", starter: "<form>\n  \n</form>", expected: ["<label", "for=", "type=\"email\"", "required", "<textarea", "type=\"submit\""], hint: "Input бүр label-тай бол keyboard болон screen reader хэрэглэгчдэд ойлгомжтой.", xp: 30 }, checkpoint: { question: "Form дээр заавал бөглөх талбарын attribute аль нь вэ?", choices: ["required", "checked", "hidden"], answer: 0, explanation: "`required` нь submit-ийн өмнө browser validation ажиллуулна." } },
  { id: "html-accessibility-project", order: 6, title: "Metadata, accessibility ба mini project", duration: "40 мин", summary: "SEO, accessibility болон semantic бүтцээ нэг мини хичээлийн хуудас болгон нэгтгэнэ.", keywords: [{ term: "meta name=\"viewport\"", meaning: "Mobile viewport-ийг зөв тохируулна." }, { term: "meta name=\"description\"", meaning: "Хайлтын системд товч тайлбар өгнө." }, { term: "aria-label", meaning: "Харагдах текстгүй control-д нэр өгнө." }, { term: "<button>", meaning: "Үйлдэл хийх control; navigation-д a биш button хэрэглэнэ." }, { term: "<label>", meaning: "Form field-ийн ил тод нэр." }, { term: "alt", meaning: "Зургийн зориулалтын текстэн тайлбар." }], code: "<head>\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n  <meta name=\"description\" content=\"HTML сурах мини хичээл\" />\n</head>\n<body>\n  <main aria-label=\"HTML хичээлийн агуулга\">...</main>\n</body>", challenge: { prompt: "Өмнөх 5 хичээлийн element-үүдийг ашиглан өөрийн 'HTML cheat sheet' хуудасны semantic outline бүтээ. Metadata, main, section, list, холбоос, form оруул.", starter: "<!doctype html>\n<html lang=\"mn\">\n  <head>\n  </head>\n  <body>\n  </body>\n</html>", expected: ["name=\"viewport\"", "<main", "<section", "<ul", "<a", "<form"], hint: "Эхлээд outline-аа semantic element-ээр, дараа нь жижиг content-оор дүүргэ.", xp: 50 }, checkpoint: { question: "Navigation хийх элемент аль нь вэ?", choices: ["<button>", "<a href>", "<div>"], answer: 1, explanation: "Өөр URL эсвэл hash руу шилжихэд anchor element хэрэглэнэ." } },
];

const cssLessons: PathLesson[] = [
  { id: "css-selectors-cascade", order: 1, title: "Selector, cascade, specificity", duration: "28 мин", summary: "CSS аль element-д үйлчлэх, зөрчилдөх rule-ийг browser хэрхэн сонгодгийг ойлгоно.", keywords: [{ term: "type selector", meaning: "`p {}` шиг tag-аар сонгоно." }, { term: ".class", meaning: "Давтан ашиглах class selector." }, { term: "#id", meaning: "Нэг онцгой element-ийн selector." }, { term: "descendant", meaning: "`.card p` шиг доторх element сонгоно." }, { term: ":hover", meaning: "Pointer hover state." }, { term: "specificity", meaning: "Зөрчилдөх rule-ийн давуу эрх." }, { term: "inherit", meaning: "Эцэг element-ээс өвлөгдөх шинж." }], code: ".lesson-card { color: #173b39; }\n.lesson-card p { color: #52666c; }\n.lesson-card a:hover { color: #0f766e; }", challenge: { prompt: "`.lesson-card` class-д border өг. Доторх paragraph-г өөр өнгөтэй, link hover үед ногоон болго.", starter: ".lesson-card {\n}\n", expected: [".lesson-card", "border", ".lesson-card p", ":hover"], hint: "Element-ийн доторх paragraph-г `.lesson-card p` гэж сонгоно.", xp: 20 }, checkpoint: { question: "`.card` selector ямар attribute дээр тулгуурладаг вэ?", choices: ["class", "id", "name"], answer: 0, explanation: "Цэгтэй selector нь class attribute-г сонгодог." } },
  { id: "css-values-box", order: 2, title: "Өнгө, unit, box model", duration: "35 мин", summary: "Content, padding, border, margin-ийн ялгаа болон relative хэмжээсийг дадлагаар ойлгоно.", keywords: [{ term: "color", meaning: "Текстийн өнгө." }, { term: "background", meaning: "Element-ийн дэвсгэр." }, { term: "px, rem, %, vw", meaning: "Түгээмэл хэмжээсийн unit." }, { term: "padding", meaning: "Content ба border-ын доторх зай." }, { term: "border", meaning: "Element-ийн хүрээ." }, { term: "margin", meaning: "Element-ийн гаднах зай." }, { term: "box-sizing", meaning: "Width/height тооцоолох горим." }], code: ".card {\n  box-sizing: border-box;\n  max-width: 42rem;\n  margin: 2rem auto;\n  padding: 1.5rem;\n  border: 1px solid #d8ded9;\n  background: #fffdf7;\n}", challenge: { prompt: "`.challenge` box-д max-width, auto margin, padding, border, background өг.", starter: ".challenge {\n}\n", expected: ["max-width", "margin", "padding", "border", "background"], hint: "Төвлөрүүлэхэд `margin: 0 auto` ашигла.", xp: 25 }, checkpoint: { question: "Content ба border-ын хоорондох зай аль нь вэ?", choices: ["margin", "padding", "gap"], answer: 1, explanation: "Padding нь element-ийн дотоод зай юм." } },
  { id: "css-typography", order: 3, title: "Typography ба visual hierarchy", duration: "26 мин", summary: "Уншихад амар текстийн хэмжээ, жин, мөр хоорондын зай, contrast-ийг тохируулна.", keywords: [{ term: "font-family", meaning: "Font stack сонгоно." }, { term: "font-size", meaning: "Текстийн хэмжээ." }, { term: "font-weight", meaning: "Текстийн жин." }, { term: "line-height", meaning: "Мөр хоорондын зай." }, { term: "letter-spacing", meaning: "Үсэг хоорондын зай." }, { term: "text-align", meaning: "Текстийн тэгшилгээ." }, { term: "contrast", meaning: "Text/background ялгарал." }], code: ".lesson-title {\n  font-family: Georgia, serif;\n  font-size: clamp(2rem, 5vw, 4rem);\n  line-height: .96;\n  letter-spacing: -.05em;\n}", challenge: { prompt: "`.lesson-title`-д serif font stack, responsive font-size, compact line-height тохируул.", starter: ".lesson-title {\n}\n", expected: ["font-family", "font-size", "line-height"], hint: "`clamp(min, fluid, max)` нь responsive текстэд тохиромжтой.", xp: 20 }, checkpoint: { question: "Мөр хоорондын зайг аль property удирдах вэ?", choices: ["line-height", "font-weight", "opacity"], answer: 0, explanation: "`line-height` нь line box-ийн өндрийг удирдана." } },
  { id: "css-flex", order: 4, title: "Flexbox layout", duration: "35 мин", summary: "Нэг тэнхлэгт элементүүдийг байрлуулах, зай хуваарилах, responsive row/column болгоно.", keywords: [{ term: "display: flex", meaning: "Flex formatting context нээнэ." }, { term: "flex-direction", meaning: "Main axis-ийн чиглэл." }, { term: "justify-content", meaning: "Main axis дагуу байрлуулна." }, { term: "align-items", meaning: "Cross axis дагуу тэгшилнэ." }, { term: "gap", meaning: "Flex item хоорондын зай." }, { term: "flex-wrap", meaning: "Зай хүрэхгүй үед мөр шилжүүлнэ." }, { term: "flex: 1", meaning: "Чөлөөт зайг эзлэх өсөлтийн shorthand." }], code: ".lesson-actions {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  gap: 1rem;\n  flex-wrap: wrap;\n}", challenge: { prompt: "Title ба button-ыг нэг мөрөнд зайтай байрлуулах `.actions` flex layout бич. Mobile дээр wrap хийх боломжоор ханга.", starter: ".actions {\n}\n", expected: ["display: flex", "justify-content", "gap", "flex-wrap"], hint: "`space-between` нь эхлэл ба төгсгөл рүү item-уудыг тараана.", xp: 30 }, checkpoint: { question: "Flex item хоорондын тогтмол зайд аль property хамгийн тохиромжтой вэ?", choices: ["gap", "padding", "float"], answer: 0, explanation: "`gap` нь flex болон grid item хоорондын зайг удирдана." } },
  { id: "css-grid-responsive", order: 5, title: "Grid ба responsive design", duration: "40 мин", summary: "Хоёр хэмжээст layout болон жижиг дэлгэцийн breakpoint-ийг бүтээнэ.", keywords: [{ term: "display: grid", meaning: "Grid layout нээнэ." }, { term: "grid-template-columns", meaning: "Баганын track тодорхойлно." }, { term: "minmax()", meaning: "Track-ийн minimum/maximum хэмжээс." }, { term: "repeat()", meaning: "Давтагдах grid track." }, { term: "@media", meaning: "Viewport зэрэг нөхцөлт rule." }, { term: "max-width", meaning: "Mobile-first breakpoint-д ашиглана." }, { term: "clamp()", meaning: "Fluid хэмжээ сонгоно." }], code: ".module-grid {\n  display: grid;\n  grid-template-columns: repeat(3, minmax(0, 1fr));\n  gap: 1rem;\n}\n@media (max-width: 720px) {\n  .module-grid { grid-template-columns: 1fr; }\n}", challenge: { prompt: "Desktop дээр 3 багана, 720px-ээс доош 1 багана болох `.module-grid` бич.", starter: ".module-grid {\n}\n", expected: ["display: grid", "grid-template-columns", "@media", "max-width: 720px"], hint: "Media query дотор `.module-grid`-ийн columns-ыг дахин тодорхойл.", xp: 35 }, checkpoint: { question: "Хоёр хэмжээст мөр, баганатай layout-д аль систем тохиромжтой вэ?", choices: ["Grid", "Flexbox", "inline"], answer: 0, explanation: "CSS Grid нь rows, columns-ыг хамтад нь удирдана." } },
  { id: "css-motion-project", order: 6, title: "Transition, animation ба responsive project", duration: "42 мин", summary: "Interactive state, motion, reduced-motion зэргийг хамарсан responsive card project хийнэ.", keywords: [{ term: "transition", meaning: "State хоорондын зөөлөн шилжилт." }, { term: "transform", meaning: "Move/scale/rotate; performance-д ээлтэй." }, { term: "opacity", meaning: "Тунгалагшил." }, { term: "@keyframes", meaning: "Animation frame sequence." }, { term: "animation", meaning: "Keyframe animation ашиглана." }, { term: "prefers-reduced-motion", meaning: "Motion багасгах user preference." }, { term: ":focus-visible", meaning: "Keyboard focus-ийн харагдах төлөв." }], code: ".card { transition: transform 180ms cubic-bezier(.23,1,.32,1); }\n.card:hover { transform: translateY(-4px); }\n.card:focus-visible { outline: 3px solid #0f766e; }\n@media (prefers-reduced-motion: reduce) { .card { transition: none; } }", challenge: { prompt: "Hover үед дээш хөдөлдөг, keyboard focus нь тод харагддаг, reduced motion хүнд animation-гүй card rule бич.", starter: ".card {\n}\n", expected: ["transition", ":hover", "transform", ":focus-visible", "prefers-reduced-motion"], hint: "User-ийн accessibility preference-г media query-ээр хүндэл.", xp: 50 }, checkpoint: { question: "Motion багасгах user preference-ийг ямар media query шалгах вэ?", choices: ["prefers-reduced-motion", "orientation", "hover"], answer: 0, explanation: "`prefers-reduced-motion` нь хөдөлгөөн багасгах preference-г илэрхийлнэ." } },
];

const javascriptLessons: PathLesson[] = [
  { id: "js-values", order: 1, title: "Хувьсагч ба өгөгдлийн төрөл", duration: "28 мин", summary: "JavaScript-ийн value, const/let, string/number/boolean/null/undefined-ийн үндсийг туршина.", keywords: [{ term: "const", meaning: "Дахин оноохгүй binding." }, { term: "let", meaning: "Дахин оноож болох binding." }, { term: "string", meaning: "Текст утга." }, { term: "number", meaning: "Тоон утга." }, { term: "boolean", meaning: "true/false." }, { term: "null", meaning: "Зориуд хоосон утга." }, { term: "typeof", meaning: "Value-ийн төрлийг шалгана." }], code: "const course = \"JavaScript\";\nlet xp = 0;\nconst unlocked = xp > 10;\nconsole.log(typeof course, unlocked);", challenge: { prompt: "`course` нэртэй const string, `xp` нэртэй let number, `isReady` нэртэй boolean үүсгээд console.log хий.", starter: "", expected: ["const course", "let xp", "const isReady", "console.log"], hint: "Дахин өөрчлөх XP-д `let`, тогтмол course нэрэнд `const` хэрэглэ.", xp: 20 }, checkpoint: { question: "Дахин оноохгүй binding-д аль keyword тохирох вэ?", choices: ["const", "let", "var"], answer: 0, explanation: "`const` binding-ийг дахин оноохыг хориглодог." } },
  { id: "js-control-flow", order: 2, title: "Operator ба control flow", duration: "35 мин", summary: "Comparison, logical operator, if/else, switch, loop-оор шийдвэрийн логик бичнэ.", keywords: [{ term: "===", meaning: "Type болон value хатуу тэнцүү эсэх." }, { term: "&&, ||, !", meaning: "Logical operator." }, { term: "if / else", meaning: "Нөхцөлт салаалалт." }, { term: "switch", meaning: "Олон салаат сонголт." }, { term: "for", meaning: "Тоолууртай давталт." }, { term: "for...of", meaning: "Iterable item-уудаар давтах." }, { term: "break / continue", meaning: "Давталтын урсгал удирдах." }], code: "const score = 80;\nif (score >= 70) {\n  console.log(\"Challenge нээгдлээ\");\n} else {\n  console.log(\"Дахин оролдоорой\");\n}", challenge: { prompt: "`score` 70-аас их буюу тэнцүү бол 'pass', бусад үед 'retry' хэвлэдэг if/else бич.", starter: "const score = 72;\n\n", expected: ["if", "score >= 70", "else", "console.log"], hint: "Нөхцөлийг `if (...) {}` дотор бичиж, эсрэг хувилбарт `else` ашигла.", xp: 25 }, checkpoint: { question: "Type болон value хоёуланг нь шалгах оператор аль нь вэ?", choices: ["==", "===", "="], answer: 1, explanation: "`===` нь strict equality шалгана." } },
  { id: "js-functions-arrays", order: 3, title: "Function, array, scope", duration: "38 мин", summary: "Давтагдах логикийг function болгон задлаж, array data-г map/filter ашиглан хувиргана.", keywords: [{ term: "function", meaning: "Named reusable block." }, { term: "return", meaning: "Function-ийн үр дүн буцаана." }, { term: "parameter", meaning: "Function input-ын нэр." }, { term: "scope", meaning: "Хувьсагчийн харагдах муж." }, { term: "array", meaning: "Дараалсан value collection." }, { term: "map()", meaning: "Array item бүрийг хувиргана." }, { term: "filter()", meaning: "Нөхцөлд тохирох item-уудыг шүүнэ." }], code: "const lessons = [\"HTML\", \"CSS\", \"JS\"];\nfunction badge(name) { return `✓ ${name}`; }\nconsole.log(lessons.map(badge));", challenge: { prompt: "`formatLesson(name)` function бичиж `Lesson: ${name}` буцаа. Дараа нь lessons array дээр map ашигла.", starter: "const lessons = [\"HTML\", \"CSS\"];\n\n", expected: ["function formatLesson", "return", ".map("], hint: "Function-ийг map-д callback болгон өгөх эсвэл arrow function ашиглаж болно.", xp: 30 }, checkpoint: { question: "Function-ийн үр дүнг caller руу буцаах keyword аль нь вэ?", choices: ["return", "yield", "break"], answer: 0, explanation: "`return` нь function-ийг дуусгаж value буцаадаг." } },
  { id: "js-objects-modules", order: 4, title: "Object, destructuring, module", duration: "35 мин", summary: "Холбоотой data-г object-д хадгалж, modern module-аар кодоо хуваана.", keywords: [{ term: "object", meaning: "Key-value data structure." }, { term: "property", meaning: "Object-ийн key/value." }, { term: "destructuring", meaning: "Object/array-аас value задлах." }, { term: "?.", meaning: "Optional chaining." }, { term: "export", meaning: "Module-оос value гаргана." }, { term: "import", meaning: "Өөр module-ийн value авна." }, { term: "default", meaning: "Module-ийн default export." }], code: "export const lesson = { title: \"DOM\", xp: 35 };\nconst { title, xp } = lesson;\nconsole.log(`${title}: ${xp}`);", challenge: { prompt: "`learner` object-д name, level key хий. Destructuring ашиглан хоёр value-ийг авч console.log бич.", starter: "const learner = {\n  name: \"Naraa\",\n  level: 2,\n};\n", expected: ["const { name, level }", "console.log"], hint: "Object-ийн key нэртэй ижил variable хэрэгтэй бол `{ name, level }` гэж задлана.", xp: 25 }, checkpoint: { question: "Object-оос `name` value-г задлах modern syntax аль нь вэ?", choices: ["const { name } = user", "const name in user", "user -> name"], answer: 0, explanation: "Destructuring syntax нь object-ийн property-г variable болгож гаргана." } },
  { id: "js-dom-events", order: 5, title: "DOM, event, хэрэглэгчийн үйлдэл", duration: "45 мин", summary: "Document-оос element сонгож, event listener-ээр UI-г өөрчилнө.", keywords: [{ term: "document.querySelector", meaning: "Эхний matching DOM element сонгоно." }, { term: "querySelectorAll", meaning: "Бүх matching element сонгоно." }, { term: "addEventListener", meaning: "Event handler бүртгэнэ." }, { term: "click", meaning: "Pointer/keyboard click event." }, { term: "event.preventDefault", meaning: "Default browser action зогсооно." }, { term: "textContent", meaning: "Аюулгүй plain text өөрчилнө." }, { term: "classList", meaning: "CSS class add/remove/toggle." }], code: "const button = document.querySelector(\"#start\");\nconst output = document.querySelector(\"#status\");\nbutton.addEventListener(\"click\", () => {\n  output.textContent = \"Challenge эхэллээ\";\n});", challenge: { prompt: "`#check` button click хийхэд `#result` element-ийн textContent-ийг 'Зөв!' болго.", starter: "const button = document.querySelector(\"#check\");\nconst result = document.querySelector(\"#result\");\n", expected: ["addEventListener", "click", "result.textContent"], hint: "Callback function event болох үед л ажиллана.", xp: 35 }, checkpoint: { question: "DOM event handler бүртгэх method аль нь вэ?", choices: ["addEventListener", "querySelector", "append"], answer: 0, explanation: "`addEventListener` нь event type ба callback авдаг." } },
  { id: "js-async-errors", order: 6, title: "Async, fetch, error handling", duration: "45 мин", summary: "Network хариу хүлээх async flow, JSON, try/catch, finally-г ойлгож жижиг data loader бичнэ.", keywords: [{ term: "async", meaning: "Promise буцаах function-г тэмдэглэнэ." }, { term: "await", meaning: "Promise resolve болохыг хүлээнэ." }, { term: "fetch", meaning: "HTTP request эхлүүлнэ." }, { term: "Response.ok", meaning: "HTTP response амжилттай эсэх." }, { term: "json()", meaning: "Response body-г JSON болгон уншина." }, { term: "try/catch", meaning: "Error барих." }, { term: "finally", meaning: "Амжилт/алдаанаас үл хамааран ажиллах block." }], code: "async function loadLesson() {\n  try {\n    const response = await fetch(\"/api/lesson\");\n    if (!response.ok) throw new Error(\"Load failed\");\n    return await response.json();\n  } catch (error) {\n    console.error(error);\n  }\n}", challenge: { prompt: "Async function дотор fetch дуудаж, response.ok false бол Error шид. Error-ийг catch дотор console.error хийнэ.", starter: "async function load() {\n  \n}\n", expected: ["await fetch", "response.ok", "throw new Error", "catch"], hint: "Network алдаа болон HTTP алдааг хоёуланг нь handle хий.", xp: 50 }, checkpoint: { question: "Promise resolve болохыг function дотор хүлээх keyword аль нь вэ?", choices: ["await", "yield", "pause"], answer: 0, explanation: "`await` нь async function дотор Promise-ийн үр дүнг хүлээнэ." } },
];

const pythonLessons: PathLesson[] = [
  { id: "py-syntax-values", order: 1, title: "Python syntax, variable, print", duration: "25 мин", summary: "Indentation, variable, үндсэн data type болон print function-оор кодын эхлэлийг тавина.", keywords: [{ term: "print()", meaning: "Console-д output хэвлэнэ." }, { term: "=", meaning: "Variable-д value онооно." }, { term: "str", meaning: "Text type." }, { term: "int, float", meaning: "Integer, decimal number." }, { term: "bool", meaning: "True/False." }, { term: "None", meaning: "Утга байхгүйг илэрхийлнэ." }, { term: "# comment", meaning: "Кодын тайлбар." }], code: "course = \"Python\"\nlevel = 1\nready = True\nprint(f\"{course}: level {level}, ready={ready}\")", challenge: { prompt: "name, level, is_ready гэсэн variable үүсгэж f-string ашиглан нэг мөр output хэвлэ.", starter: "", expected: ["name =", "level =", "is_ready =", "print(f"], hint: "Python string interpolation-д `f\"...{name}...\"` хэлбэр ашигла.", xp: 20 }, checkpoint: { question: "Python code block-ийг юу тодорхойлдог вэ?", choices: ["Догол мөр", "Хаалт", "Таслал"], answer: 0, explanation: "Python нь indentation-аар block-ийн хилийг тогтоодог." } },
  { id: "py-collections", order: 2, title: "String, list, tuple, set, dict", duration: "40 мин", summary: "Өгөгдлийн бүтэц бүрийг ямар асуудалд сонгохоо жишээгээр ойлгоно.", keywords: [{ term: "list []", meaning: "Дараалалтай, өөрчлөгдөх collection." }, { term: "tuple ()", meaning: "Дараалалтай, өөрчлөгдөхгүй collection." }, { term: "set {}", meaning: "Давхардалгүй unique value." }, { term: "dict {key: value}", meaning: "Key-value mapping." }, { term: "append()", meaning: "List-ийн төгсгөлд item нэмнэ." }, { term: "len()", meaning: "Collection-ийн урт." }, { term: "in", meaning: "Агуулж буй эсэхийг шалгана." }], code: "skills = [\"HTML\", \"CSS\"]\nlearner = {\"name\": \"Naraa\", \"xp\": 80}\nskills.append(\"Python\")\nprint(learner[\"name\"], len(skills))", challenge: { prompt: "`topics` list, `profile` dict үүсгэ. List-д нэг шинэ item append хийгээд dict-ээс name хэвлэ.", starter: "", expected: ["topics = [", "profile = {", ".append(", "profile[\"name\"]"], hint: "Dictionary value-г key-ээр нь дөрвөлжин хаалтаар авна.", xp: 25 }, checkpoint: { question: "Key-value pair хадгалах Python бүтэц аль нь вэ?", choices: ["dict", "list", "tuple"], answer: 0, explanation: "Dictionary нь key-аар value рүү ханддаг." } },
  { id: "py-control-flow", order: 3, title: "if, for, while, range", duration: "38 мин", summary: "Шийдвэр ба давталтаар program flow-ийг удирдана.", keywords: [{ term: "if / elif / else", meaning: "Нөхцөлт салаалалт." }, { term: "for", meaning: "Iterable item-уудаар давтах." }, { term: "while", meaning: "Нөхцөл үнэн байх хугацаанд давтах." }, { term: "range()", meaning: "Тоон дараалал үүсгэнэ." }, { term: "break", meaning: "Давталтаас шууд гарна." }, { term: "continue", meaning: "Тухайн iteration-ийг алгасна." }, { term: "pass", meaning: "Хоосон block-ийн placeholder." }], code: "xp = 45\nif xp >= 50:\n    print(\"Level up\")\nelse:\n    print(\"Дахиад challenge хий\")\n\nfor step in range(1, 4):\n    print(f\"Алхам {step}\")", challenge: { prompt: "score 70-аас их бол outcome-д 'pass' оноож, түүнийг хэвлэ. Дараа нь range ашиглан 1-3 хүртэл хэвлэ.", starter: "score = 72\n\nif score >= 70:\n    outcome = \"pass\"\nelse:\n    outcome = \"retry\"\n\nprint(outcome)\nfor step in range(1, 4):\n    print(step)", expected: ["if score >= 70", "else:", "for", "range("], hint: "Colon-ийн дараах мөр заавал доголтой эхэлнэ. `outcome`-ийг condition-ийн хоёр салаанд онооно.", xp: 30 }, checkpoint: { question: "List item бүрээр давтахад аль statement тохиромжтой вэ?", choices: ["for", "match", "def"], answer: 0, explanation: "`for` нь iterable-ийн item-уудаар дарааллаар явна." } },
  { id: "py-functions", order: 4, title: "Function, parameter, comprehension", duration: "40 мин", summary: "Function-оор логикоо дахин ашиглаж, list comprehension-оор data transformation хийнэ.", keywords: [{ term: "def", meaning: "Function тодорхойлно." }, { term: "return", meaning: "Function-оос value буцаана." }, { term: "parameter", meaning: "Function input." }, { term: "default argument", meaning: "Default value-той parameter." }, { term: "*args, **kwargs", meaning: "Олон аргумент цуглуулах." }, { term: "lambda", meaning: "Жижиг anonymous function." }, { term: "comprehension", meaning: "Collection-ийг compact байдлаар үүсгэнэ." }], code: "def badge(name, level=1):\n    return f\"{name} · L{level}\"\n\nlevels = [1, 2, 3]\nlabels = [badge(\"Learner\", level) for level in levels]\nprint(labels)", challenge: { prompt: "`is_passed(score)` function бичиж score >= 70 boolean буцаа. Дараа нь list comprehension-оор тэнцсэн score-уудыг шүү.", starter: "scores = [40, 70, 88, 55]\n\n", expected: ["def is_passed", "return", "for", "if"], hint: "Comprehension: `[value for value in values if condition]`.", xp: 35 }, checkpoint: { question: "Python function эхлүүлэх keyword аль нь вэ?", choices: ["def", "function", "func"], answer: 0, explanation: "`def` keyword нь function definition эхлүүлдэг." } },
  { id: "py-modules-files", order: 5, title: "Module, file, JSON", duration: "42 мин", summary: "Кодоо module болгон хувааж, file болон JSON data уншиж бичих үндсийг сурна.", keywords: [{ term: "import", meaning: "Module оруулна." }, { term: "from ... import", meaning: "Тодорхой нэр import хийнэ." }, { term: "__name__", meaning: "Module script болж ажиллаж буй эсэх." }, { term: "with open", meaning: "File-ийг аюулгүй нээж хаана." }, { term: "read(), write()", meaning: "File input/output." }, { term: "json.load", meaning: "JSON file-ийг Python object болгоно." }, { term: "json.dump", meaning: "Python object-ийг JSON болгон бичнэ." }], code: "import json\n\nwith open(\"progress.json\", encoding=\"utf-8\") as file:\n    progress = json.load(file)\nprint(progress)", challenge: { prompt: "Sandbox-д бэлэн байгаа `notes.txt` файлыг `with open` ашиглан UTF-8 encoding-оор уншаад `content` variable-д хадгал.", starter: "with open(\"notes.txt\", encoding=\"utf-8\") as file:\n    content = file.read()\n\nprint(content)", expected: ["with open(", "encoding=\"utf-8\"", "as file", ".read("], hint: "`with` block дуусахад file автоматаар хаагдана. `content = file.read()` гэсэн бодит үр дүнг validator шалгана.", xp: 35 }, checkpoint: { question: "File-ийг найдвартай хаах контекст manager syntax аль нь вэ?", choices: ["with open", "open forever", "file.start"], answer: 0, explanation: "`with open(...) as file:` нь resource cleanup-г баталгаажуулна." } },
  { id: "py-errors-classes", order: 6, title: "Exception, class, mini project", duration: "50 мин", summary: "Error handling, class-ийн үндэс болон суралцагчийн XP tracker mini project-оор Python замаа баталгаажуулна.", keywords: [{ term: "try / except", meaning: "Exception барих." }, { term: "raise", meaning: "Exception зориуд үүсгэх." }, { term: "finally", meaning: "Ямар ч нөхцөлд ажиллах cleanup." }, { term: "class", meaning: "Object blueprint." }, { term: "__init__", meaning: "Object initialize хийх method." }, { term: "self", meaning: "Одоогийн object reference." }, { term: "isinstance", meaning: "Object-ийн type шалгах." }], code: "class Learner:\n    def __init__(self, name):\n        self.name = name\n        self.xp = 0\n\n    def add_xp(self, amount):\n        if amount < 0:\n            raise ValueError(\"XP сөрөг байж болохгүй\")\n        self.xp += amount\n\ntry:\n    learner = Learner(\"Naraa\")\n    learner.add_xp(25)\nexcept ValueError as error:\n    print(error)", challenge: { prompt: "`Learner` class хийж, name болон xp property оноо. `add_xp` method нь xp-г нэмдэг байх ёстой.", starter: "class Learner:\n    \n", expected: ["class Learner", "def __init__", "self.name", "def add_xp", "self.xp +="], hint: "Instance property бүрийг `self.`-ээр хадгална.", xp: 55 }, checkpoint: { question: "Exception барих Python block аль нь вэ?", choices: ["try/except", "if/else", "for/in"], answer: 0, explanation: "Error үүсч болзошгүй code-ийг try, handler-ийг except-д бичнэ." } },
];

type AtomicLesson = { id: string; term: string; title: string; meaning: string; code: string; starter: string; expected: string[]; quest: "build" | "debug" | "predict" | "timed" };

const htmlAtomic: AtomicLesson[] = [
  { id: "html-what-is-html", term: "HTML", title: "HTML гэж юу вэ?", meaning: "HTML нь web page-ийн бүтэц болон утгыг тэмдэглэдэг markup хэл.", code: "<!doctype html>\n<html lang=\"mn\"><body>Сайн байна уу</body></html>", starter: "<!doctype html>\n<html lang=\"mn\">\n  <body>\n    CodeCraft\n  </body>\n</html>", expected: ["html[lang='mn']", "body"], quest: "build" },
  { id: "html-h1", term: "<h1>", title: "h1 — гол гарчиг", meaning: "Хуудасны хамгийн чухал гарчгийг илэрхийлнэ.", code: "<h1>HTML хичээл</h1>", starter: "<h1>Миний гол гарчиг</h1>", expected: ["h1"], quest: "build" },
  { id: "html-p", term: "<p>", title: "p — догол мөр", meaning: "Нэг санааг догол мөр хэлбэрээр илэрхийлнэ.", code: "<p>Энэ бол нэг догол мөр.</p>", starter: "<p>CodeCraft дээр HTML сурч байна.</p>", expected: ["p"], quest: "predict" },
  { id: "html-a", term: "<a href>", title: "a ба href — холбоос", meaning: "Өөр page эсвэл resource руу чиглүүлэх anchor element.", code: "<a href=\"/learn\">Хичээл рүү</a>", starter: "<a href=\"https://developer.mozilla.org\">MDN</a>", expected: ["a[href]"], quest: "build" },
  { id: "html-img", term: "<img alt>", title: "img ба alt — зураг", meaning: "src нь зургийн source, alt нь утгатай текстэн тайлбар.", code: "<img src=\"map.png\" alt=\"Сургалтын зам\" />", starter: "<img src=\"lesson.png\" alt=\"HTML lesson diagram\" />", expected: ["img[alt]"], quest: "debug" },
  { id: "html-ul", term: "<ul>", title: "ul — дараалалгүй жагсаалт", meaning: "Bullet-тай ижил ангиллын item-уудыг агуулна.", code: "<ul><li>HTML</li><li>CSS</li></ul>", starter: "<ul><li>HTML</li><li>CSS</li></ul>", expected: ["ul", "li"], quest: "build" },
  { id: "html-ol", term: "<ol>", title: "ol — дараалалтай жагсаалт", meaning: "Алхам, дараалал чухал item-уудыг numbered list болгоно.", code: "<ol><li>Унш</li><li>Кодло</li></ol>", starter: "<ol><li>Унш</li><li>Кодло</li></ol>", expected: ["ol", "li"], quest: "build" },
  { id: "html-div", term: "<div>", title: "div — ерөнхий block", meaning: "Semantic element тохирохгүй үед layout grouping хийх block container.", code: "<div class=\"card\">...</div>", starter: "<div class=\"lesson-card\">HTML lesson</div>", expected: ["div"], quest: "build" },
  { id: "html-span", term: "<span>", title: "span — inline group", meaning: "Текстийн жижиг хэсгийг inline байдлаар ялгаж тэмдэглэнэ.", code: "<p>Үнэ: <span>20 XP</span></p>", starter: "<p>Quest: <span>20 XP</span></p>", expected: ["span"], quest: "build" },
  { id: "html-header", term: "<header>", title: "header — оршил хэсэг", meaning: "Page эсвэл section-ийн title, logo, оршил navigation-г агуулна.", code: "<header><h1>CodeCraft</h1></header>", starter: "<header><h1>HTML path</h1></header>", expected: ["header h1"], quest: "build" },
  { id: "html-nav", term: "<nav>", title: "nav — navigation", meaning: "Гол navigation link-үүдийн semantic container.", code: "<nav><a href=\"#lessons\">Хичээл</a></nav>", starter: "<nav><a href=\"#start\">Эхлэх</a></nav>", expected: ["nav a[href]"], quest: "build" },
  { id: "html-main", term: "<main>", title: "main — гол агуулга", meaning: "Page-ийн цорын ганц, давтагдашгүй үндсэн агуулгыг заана.", code: "<main><h1>Хичээл</h1></main>", starter: "<main><p>Энэ бол гол content.</p></main>", expected: ["main"], quest: "predict" },
  { id: "html-section", term: "<section>", title: "section — сэдвийн бүлэг", meaning: "Өөрийн гарчигтай холбоотой content group.", code: "<section><h2>Forms</h2></section>", starter: "<section><h2>HTML tags</h2><p>Сурцгаая.</p></section>", expected: ["section h2"], quest: "build" },
  { id: "html-article", term: "<article>", title: "article — бие даасан контент", meaning: "Дангаараа түгээгдэж, ойлгогдож болох нийтлэл эсвэл post.", code: "<article><h2>Lesson note</h2><p>...</p></article>", starter: "<article><h2>Tag note</h2><p>h1 бол гол гарчиг.</p></article>", expected: ["article h2", "article p"], quest: "build" },
  { id: "html-aside", term: "<aside>", title: "aside — нэмэлт тайлбар", meaning: "Гол content-оос тусдаа боловч холбоотой hint, glossary, ad зэрэг content.", code: "<aside>Hint: alt бүү мартаарай.</aside>", starter: "<aside>Hint: semantic tag сонго.</aside>", expected: ["aside"], quest: "debug" },
  { id: "html-footer", term: "<footer>", title: "footer — төгсгөлийн хэсэг", meaning: "Copyright, contact, related link зэрэг төгсгөлийн metadata.", code: "<footer>© CodeCraft</footer>", starter: "<footer>© 2026 CodeCraft</footer>", expected: ["footer"], quest: "build" },
  { id: "html-table", term: "<table>", title: "table — хүснэгт", meaning: "Мөр, баганад зохион байгуулагдсан харьцуулж болох data.", code: "<table><thead><tr><th>Tag</th></tr></thead><tbody><tr><td>h1</td></tr></tbody></table>", starter: "<table><thead><tr><th scope=\"col\">Tag</th></tr></thead><tbody><tr><td>h1</td></tr></tbody></table>", expected: ["table", "thead th[scope='col']", "tbody td"], quest: "build" },
  { id: "html-form", term: "<form>", title: "form — input group", meaning: "Хэрэглэгчийн input-уудыг submit үйлдэлтэйгээр нэгтгэнэ.", code: "<form><button type=\"submit\">Илгээх</button></form>", starter: "<form><button type=\"submit\">Илгээх</button></form>", expected: ["form", "button[type='submit']"], quest: "build" },
  { id: "html-label", term: "<label for>", title: "label — input нэр", meaning: "Input-ын утгыг тодорхойлж, for/id-гаар accessibility холбоно.", code: "<label for=\"email\">Имэйл</label><input id=\"email\" />", starter: "<label for=\"name\">Нэр</label><input id=\"name\" />", expected: ["label[for]", "input[id]"], quest: "build" },
  { id: "html-input", term: "<input type>", title: "input — нэг мөр input", meaning: "type attribute нь email, password, checkbox гэх мэт input behavior-г сонгоно.", code: "<input type=\"email\" />", starter: "<input type=\"email\" />", expected: ["input[type='email']"], quest: "build" },
  { id: "html-textarea", term: "<textarea>", title: "textarea — олон мөр input", meaning: "Урт comment, feedback зэрэг олон мөр text авна.", code: "<textarea></textarea>", starter: "<textarea>Feedback...</textarea>", expected: ["textarea"], quest: "build" },
  { id: "html-button", term: "<button>", title: "button — үйлдэл", meaning: "Form submit эсвэл JavaScript action хийх interactive control.", code: "<button type=\"button\">Шалгах</button>", starter: "<button type=\"button\">Quest эхлэх</button>", expected: ["button[type='button']"], quest: "build" },
  { id: "html-required", term: "required", title: "required — заавал бөглөх", meaning: "Form input-ыг submit хийхийн өмнө browser validation шаардана.", code: "<input type=\"email\" required />", starter: "<input type=\"email\" required />", expected: ["input[required]"], quest: "debug" },
  { id: "html-aria-label", term: "aria-label", title: "aria-label — accessibility нэр", meaning: "Харагдах label байхгүй control-д screen reader-д зориулсан нэр өгнө.", code: "<button aria-label=\"Хайх\">⌕</button>", starter: "<button aria-label=\"Мэдэгдэл харах\">Bell</button>", expected: ["button[aria-label]"], quest: "build" },
];

function cssAtom(id: string, term: string, title: string, meaning: string, property: string, value: string, quest: AtomicLesson["quest"] = "build"): AtomicLesson { const selector = ".lesson-card"; return { id, term, title, meaning, code: `${selector} { ${property}: ${value}; }`, starter: `${selector} {\n  ${property}: ${value};\n}`, expected: [`${selector}::${property}`], quest }; }
const cssAtomic: AtomicLesson[] = [
  cssAtom("css-what-is-css", "CSS", "CSS гэж юу вэ?", "CSS нь HTML content-ийн өнгө, хэмжээ, байрлал, motion-ийг тодорхойлно.", "color", "#173b39"),
  cssAtom("css-type-selector", "type selector", "Type selector", "Element tag нэрээр style сонгоно.", "color", "#173b39"), cssAtom("css-class-selector", ".class", "Class selector", "Дахин ашиглах class attribute-аар element сонгоно.", "padding", "1rem"), cssAtom("css-id-selector", "#id", "ID selector", "Нэг онцгой element-ийг id-аар сонгоно.", "margin", "1rem"),
  cssAtom("css-color", "color", "color — текстийн өнгө", "Text-ийн foreground color property.", "color", "#0f766e"), cssAtom("css-background", "background-color", "background-color — дэвсгэр", "Element-ийн background color.", "background-color", "#fffdf7"), cssAtom("css-font-size", "font-size", "font-size — үсгийн хэмжээ", "Text-ийн хэмжээг тохируулна.", "font-size", "1.25rem"), cssAtom("css-font-weight", "font-weight", "font-weight — жин", "Text-ийн bold/light weight.", "font-weight", "700"),
  cssAtom("css-margin", "margin", "margin — гаднах зай", "Element хоорондын гаднах зай.", "margin", "1rem"), cssAtom("css-padding", "padding", "padding — дотоод зай", "Content ба border хоорондын зай.", "padding", "1rem"), cssAtom("css-border", "border", "border — хүрээ", "Element-ийн visible хүрээ.", "border", "1px solid #d8ded9"), cssAtom("css-width", "width", "width — өргөн", "Element-ийн өргөн.", "width", "100%"),
  cssAtom("css-display", "display", "display — layout mode", "Element box хэрхэн layout-д оролцохыг сонгоно.", "display", "block"), cssAtom("css-flex", "display:flex", "Flex container", "Нэг тэнхлэгт flexible layout нээнэ.", "display", "flex"), cssAtom("css-justify", "justify-content", "justify-content", "Flex/grid-ийн main axis spacing.", "justify-content", "space-between"), cssAtom("css-align", "align-items", "align-items", "Cross axis alignment.", "align-items", "center"),
  cssAtom("css-gap", "gap", "gap — item зай", "Flex/grid item хоорондын spacing.", "gap", "1rem"), cssAtom("css-grid", "display:grid", "Grid container", "Хоёр хэмжээст grid layout нээнэ.", "display", "grid"), cssAtom("css-grid-columns", "grid-template-columns", "Grid багана", "Grid-ийн баганын track-ууд.", "grid-template-columns", "repeat(2, 1fr)"), cssAtom("css-position", "position", "position — байрлал", "Static, relative, absolute гэх positioning mode.", "position", "relative"),
  cssAtom("css-hover", ":hover", "hover state", "Pointer hover үед style өөрчилнө.", "opacity", "0.8", "timed"), cssAtom("css-transition", "transition", "transition — шилжилт", "State солигдох motion duration.", "transition", "transform 180ms ease"), cssAtom("css-transform", "transform", "transform — хувиргалт", "Move, scale, rotate хийж layout-аас ангид хөдөлнө.", "transform", "translateY(-4px)"), cssAtom("css-animation", "animation", "animation — keyframe motion", "Keyframe sequence ашигласан хөдөлгөөн.", "animation", "pulse 1s ease"),
];

function jsAtom(id: string, term: string, title: string, meaning: string, code: string, quest: AtomicLesson["quest"] = "build"): AtomicLesson { return { id, term, title, meaning, code, starter: `${code}\nconsole.log("quest-ok");`, expected: [], quest }; }
const javascriptAtomic: AtomicLesson[] = [
  jsAtom("js-what-is-js", "JavaScript", "JavaScript гэж юу вэ?", "Browser дотор logic, event, dynamic behavior нэмдэг programming хэл.", "console.log('JavaScript')"), jsAtom("js-console-log", "console.log", "console.log — output", "Development console-д value хэвлэнэ.", "console.log('Hello')"), jsAtom("js-const", "const", "const — тогтмол binding", "Дахин оноохгүй value binding.", "const course = 'JS'"), jsAtom("js-let", "let", "let — өөрчлөгдөх binding", "Дахин оноож болох variable.", "let xp = 0; xp += 10"),
  jsAtom("js-string", "string", "string — текст", "Text value.", "const name = 'Naraa'"), jsAtom("js-number", "number", "number — тоо", "Integer болон decimal number.", "const score = 80"), jsAtom("js-boolean", "boolean", "boolean — true/false", "Логик үнэний value.", "const passed = true"), jsAtom("js-array", "array", "array — дараалал", "Ordered value collection.", "const tags = ['h1', 'p']"),
  jsAtom("js-object", "object", "object — key/value", "Холбоотой data-г key/value хэлбэрээр хадгална.", "const lesson = { title: 'h1', xp: 20 }"), jsAtom("js-if", "if", "if — нөхцөл", "Нөхцөл үнэн үед нэг branch ажиллуулна.", "if (true) { console.log('pass') }"), jsAtom("js-else", "else", "else — эсрэг branch", "if нөхцөл false үед ажиллана.", "if (false) { console.log('no') } else { console.log('pass') }"), jsAtom("js-for", "for", "for — давталт", "Тоолуур эсвэл iterable-аар давтана.", "for (let i = 0; i < 2; i += 1) { console.log(i) }"),
  jsAtom("js-while", "while", "while — нөхцөлт давталт", "Нөхцөл үнэн байх хугацаанд давтана.", "let i = 0; while (i < 1) { i += 1 }"), jsAtom("js-function", "function", "function — дахин ашиглах logic", "Parameter авч result буцааж болох function.", "function greet() { return 'hello' }"), jsAtom("js-return", "return", "return — value буцаах", "Function execution-ийг дуусгаж value буцаана.", "function xp() { return 20 }"), jsAtom("js-parameter", "parameter", "parameter — function input", "Function-д орж ирэх value-ийн нэр.", "function badge(name) { return name }"),
  jsAtom("js-map", "map", "map — хувиргалт", "Array item бүрийг шинэ array value болгоно.", "const values = [1, 2].map((n) => n * 2)"), jsAtom("js-filter", "filter", "filter — шүүлт", "Нөхцөл хангасан item-уудыг үлдээнэ.", "const values = [1, 2].filter((n) => n > 1)"), jsAtom("js-query-selector", "querySelector", "querySelector — DOM сонгох", "CSS selector-аар эхний DOM element авна.", "const button = document.querySelector('#check')"), jsAtom("js-event-listener", "addEventListener", "addEventListener — event", "Click зэрэг user event-д callback холбоно.", "document.querySelector('#check').addEventListener('click', () => console.log('pass'))"),
  jsAtom("js-text-content", "textContent", "textContent — текст солих", "DOM element-ийн plain text content-г аюулгүй шинэчилнэ.", "document.querySelector('#result').textContent = 'pass'"), jsAtom("js-async", "async", "async — Promise function", "Await ашиглах Promise-returning function.", "async function load() { return 'ok' }"), jsAtom("js-await", "await", "await — Promise хүлээх", "Async function дотор Promise resolve болохыг хүлээнэ.", "async function load() { await Promise.resolve('ok') }"), jsAtom("js-try-catch", "try/catch", "try/catch — error", "Runtime error-г барьж fallback ажиллуулна.", "try { throw new Error('x') } catch (error) { console.log('pass') }"),
];

function pyAtom(id: string, term: string, title: string, meaning: string, code: string, quest: AtomicLesson["quest"] = "build"): AtomicLesson { return { id, term, title, meaning, code, starter: `${code}\nprint('quest-ok')`, expected: [], quest }; }
const pythonAtomic: AtomicLesson[] = [
  pyAtom("py-what-is-python", "Python", "Python гэж юу вэ?", "Уншихад ойлгомжтой syntax-тэй general-purpose programming хэл.", "print('Python')"), pyAtom("py-print", "print()", "print — output", "Console output хэвлэнэ.", "print('Hello')"), pyAtom("py-variable", "=", "variable — оноолт", "Name-д value онооно.", "name = 'Naraa'"), pyAtom("py-str", "str", "str — текст", "String text type.", "name = str('Naraa')"),
  pyAtom("py-int", "int", "int — бүхэл тоо", "Integer number type.", "score = int(80)"), pyAtom("py-bool", "bool", "bool — true/false", "True/False logical type.", "passed = bool(True)"), pyAtom("py-list", "list", "list — дараалал", "Ordered mutable collection.", "tags = ['h1', 'p']"), pyAtom("py-dict", "dict", "dict — key/value", "Key-аар value авах mapping.", "lesson = {'title': 'h1'}"),
  pyAtom("py-tuple", "tuple", "tuple — өөрчлөгдөхгүй дараалал", "Immutable ordered collection.", "point = (10, 20)"), pyAtom("py-set", "set", "set — unique value", "Давхардалгүй collection.", "tags = {'h1', 'p'}"), pyAtom("py-if", "if", "if — нөхцөл", "Нөхцөл үнэн үед branch ажиллуулна.", "if True:\n    print('pass')"), pyAtom("py-elif", "elif", "elif — нэмэлт нөхцөл", "Нэмэлт condition branch.", "if False:\n    pass\nelif True:\n    print('pass')"),
  pyAtom("py-else", "else", "else — fallback", "Нөхцөл худал үед ажиллах branch.", "if False:\n    pass\nelse:\n    print('pass')"), pyAtom("py-for", "for", "for — давталт", "Iterable-ийн item бүрээр давтана.", "for tag in ['h1']:\n    print(tag)"), pyAtom("py-range", "range", "range() — тоон дараалал", "Integer sequence үүсгэж loop-д ашиглана.", "for n in range(1):\n    print(n)"), pyAtom("py-while", "while", "while — нөхцөлт давталт", "Condition үнэн байх хугацаанд давтана.", "count = 0\nwhile count < 1:\n    count += 1"),
  pyAtom("py-def", "def", "def — function", "Reusable function тодорхойлно.", "def greet():\n    return 'hello'"), pyAtom("py-return", "return", "return — result", "Function-оос value буцаана.", "def xp():\n    return 20"), pyAtom("py-parameter", "parameter", "parameter — function input", "Function input-ын нэр.", "def badge(name):\n    return name"), pyAtom("py-import", "import", "import — module", "Module-ийн code/feature ашиглана.", "import math\nprint(math.floor(1.2))"),
  pyAtom("py-with", "with", "with — context manager", "Resource-г аюулгүй нээж хаадаг block.", "with open('notes.txt', 'w') as file:\n    file.write('ok')"), pyAtom("py-open", "open", "open — file", "File object нээнэ.", "with open('notes.txt', 'w') as file:\n    file.write('ok')"), pyAtom("py-try", "try", "try — error risk", "Error үүсч болзошгүй code-г оруулна.", "try:\n    int('x')\nexcept ValueError:\n    print('pass')"), pyAtom("py-except", "except", "except — error handle", "Exception type-д хариу үйлдэл хийнэ.", "try:\n    raise ValueError()\nexcept ValueError:\n    print('pass')"), pyAtom("py-class", "class", "class — object blueprint", "Property/method-той object type тодорхойлно.", "class Learner:\n    pass"),
];

function atomicToLesson(language: LanguageId, unit: AtomicLesson, order: number): PathLesson {
  const debugStarter = language === "css" && unit.quest === "debug" ? unit.starter.replace(unit.expected[0]?.split("::")[1] ?? "", `${unit.expected[0]?.split("::")[1] ?? ""}-broken`) : language === "html" && unit.quest === "debug" && unit.starter.includes("alt=") ? unit.starter.replace("alt=", "data-alt=") : unit.starter;
  const difficulty = difficultyGuidance(order);
  return { id: unit.id, order, title: `${unit.title} · ${difficulty.label}`, duration: "12–18 мин", summary: unit.meaning, keywords: [{ term: unit.term, meaning: unit.meaning }], code: unit.code, challenge: { prompt: `${unit.term} ойлголтын ${difficulty.label.toLowerCase()} шатны code quest. ${difficulty.guidance}`, starter: debugStarter, expected: unit.expected, hint: `Эхлээд ${unit.term} ямар үүрэгтэйг жишээнээс харж, дараа нь өөрийн кодоо бүтээнэ үү.`, xp: unit.quest === "timed" ? 30 : 20, kind: unit.quest, prediction: unit.quest === "predict" ? { prompt: `Кодыг шалгахаас өмнө энэ lesson-ийн гол tag/keyword-ийг яг бичнэ үү.`, answer: unit.term } : undefined }, checkpoint: { question: `${unit.term} ямар зориулалттай вэ?`, choices: [unit.meaning, "Зөвхөн зураг оруулдаг element/property.", "Browser-ийг хаадаг command."], answer: 0, explanation: unit.meaning }, quiz: buildLessonQuiz({ lessonId: unit.id, language, term: unit.term, meaning: unit.meaning, code: unit.code, starter: debugStarter, expected: unit.expected }) };
}

const htmlDetailed = htmlAtomic.map((unit, index) => atomicToLesson("html", unit, index + 1));
const cssDetailed = cssAtomic.map((unit, index) => atomicToLesson("css", unit, index + 1));
const javascriptDetailed = javascriptAtomic.map((unit, index) => atomicToLesson("javascript", unit, index + 1));
const pythonDetailed = pythonAtomic.map((unit, index) => atomicToLesson("python", unit, index + 1));

export const languagePaths: LanguagePath[] = [
  { id: "html", label: "HTML", accent: "#E46F32", pale: "#FFF0E8", source: "https://developer.mozilla.org/en-US/docs/Web/HTML/Reference", sourceLabel: "MDN · HTML elements & attributes", description: "Element, attribute, semantic structure бүрийг нэг lesson-ээр сурч, accessibility-тэй HTML page бүтээ.", project: "Semantic HTML Portfolio", lessons: htmlDetailed },
  { id: "css", label: "CSS", accent: "#2866D4", pale: "#EAF1FF", source: "https://developer.mozilla.org/en-US/docs/Web/CSS/Reference", sourceLabel: "MDN · CSS properties & selectors", description: "Selector, property, layout, responsive motion бүрийг тусад нь туршиж visual system бүтээ.", project: "Responsive UI System", lessons: cssDetailed },
  { id: "javascript", label: "JavaScript", accent: "#B98712", pale: "#FFF8DD", source: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference", sourceLabel: "MDN · JavaScript language reference", description: "Keyword, data, function, DOM, event, async бүрийг бодит output quest-ээр батал.", project: "Interactive Learning Toolkit", lessons: javascriptDetailed },
  { id: "python", label: "Python", accent: "#3E7A58", pale: "#EAF6EE", source: "https://docs.python.org/3/tutorial/index.html", sourceLabel: "Python Docs · The Python Tutorial", description: "Python keyword болон runtime behavior бүрийг тусдаа кодын туршилтаар сур.", project: "Python Problem Solver", lessons: pythonDetailed },
  githubPath,
];

export function findPath(id: string | undefined) { return languagePaths.find((path) => path.id === id) ?? languagePaths[0]; }
export function findLesson(path: LanguagePath, lessonId: string | undefined) { return path.lessons.find((lesson) => lesson.id === lessonId) ?? path.lessons[0]; }
