/** Code Atlas Editorial: a calm public entry point leading into the authenticated learning workspace. */
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { courseModules } from "@/lib/courseData";
import { startLogin } from "@/const";
import { BadgeCheck, BookOpen, ChevronRight, CircleHelp, Code2, Compass, FlaskConical, LogOut, Play, ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";

export default function Home() {
  const [, setLocation] = useLocation();
  const { user, loading, logout } = useAuth();

  return (
    <div className="academy-home">
      <header className="site-header"><button className="brand" type="button" onClick={() => setLocation("/")}><img src="/manus-storage/codecraft-atlas-logo_9d75d0e7.png" alt="" className="brand-mark" /><span><strong>CodeCraft</strong><small>ACADEMY</small></span></button><nav className="main-nav" aria-label="Үндсэн цэс"><a href="#program">Хөтөлбөр</a><a href="#platform">Сургалтын орчин</a><a href="#sources">Эх сурвалж</a></nav><div className="home-auth">{loading ? <span className="auth-loading">Бэлтгэж байна...</span> : user ? <><span className="user-greeting">{user.name || "Суралцагч"}</span>{user.role === "admin" && <Button variant="ghost" size="sm" onClick={() => setLocation("/admin")}>Багшийн самбар</Button>}<Button size="sm" className="atlas-button" onClick={() => setLocation("/learn")}>Миний сургалт <ChevronRight size={15} /></Button><Button variant="ghost" size="icon" aria-label="Гарах" onClick={logout}><LogOut size={16} /></Button></> : <><Button variant="ghost" size="sm" onClick={startLogin}>Нэвтрэх</Button><Button size="sm" className="atlas-button" onClick={startLogin}>Бүртгүүлэх <ChevronRight size={15} /></Button></>}</div></header>
      <main><section className="new-hero"><div className="hero-route" aria-hidden="true"><span>01</span><i /></div><div className="hero-text"><p className="eyebrow"><Compass size={15} /> СУРАЛЦАХ АТЛАС · 2026</p><h1>Кодын үндсийг <em>хийж туршин</em> сур.</h1><p>HTML, CSS, JavaScript, Python-ыг хичээл, сорил, асуулт-хариулт, шууд ажилладаг лабораторитой нь уялдуулан сур.</p><div className="hero-actions"><Button className="atlas-button" onClick={user ? () => setLocation("/learn") : startLogin}>{user ? "Сургалтаа үргэлжлүүлэх" : "Үнэгүй эхлүүлэх"} <ChevronRight size={17} /></Button><a className="quiet-link" href="#platform"><Play size={14} fill="currentColor" /> Сургалтын орчинг үзэх</a></div><div className="hero-trust"><span><BadgeCheck size={16} /> Ахиц хадгалагдана</span><span><ShieldCheck size={16} /> Аюулгүй нэвтрэлт</span><span><FlaskConical size={16} /> Шууд код туршилт</span></div></div><div className="hero-visual"><img src="/manus-storage/codecraft-hero-atlas_ac8f70d7.png" alt="Код сурах атласын визуал" /><div className="visual-note"><small>СУРГАЛТЫН УРСГАЛ</small><strong>Хичээл → Сорил → Лаб</strong><p>Нэг ойлголтыг мэдээд, шалгаад, хэрэгжүүл.</p></div></div></section>
      <section id="program" className="program-section"><div className="section-intro"><div><p className="section-kicker">ДӨРВӨН ЧИГЛЭЛ</p><h2>Сууриа мэдээд, <em>холбоог нь</em> ойлго.</h2></div><p>Хэл бүрийн хичээл нь бодит дадалд тулгуурлаж, дараагийн ойлголтыг барих суурь болдог.</p></div><div className="program-grid">{courseModules.map((course) => <button key={course.id} type="button" className="program-card" onClick={user ? () => setLocation("/learn") : startLogin} style={{ "--course-color": course.color, "--course-pale": course.pale } as React.CSSProperties}><span>{course.number}</span><Code2 /><h3>{course.label}</h3><p>{course.title}</p><small>{course.lessons} хичээл · {course.duration}</small><ChevronRight className="card-arrow" size={18} /></button>)}</div></section>
      <section id="platform" className="platform-section"><div className="platform-head"><p className="section-kicker">НЭГДСЭН СУРГАЛТЫН ОРЧИН</p><h2>Уншихаас илүү, <em>хийж баталгаажуул.</em></h2></div><div className="platform-grid"><article><BookOpen /><h3>Хадгалагддаг ахиц</h3><p>Нэвтэрсэн хэрэглэгч хичээл дуусалт, сорилын оролдлогоо төхөөрөмж солигдсон ч үргэлжлүүлнэ.</p></article><article><CircleHelp /><h3>Шаталсан сорил ба хэлэлцүүлэг</h3><p>Хичээл бүрийн төгсгөлд асуулт бүрээр тайлбартай сорил, жинхэнэ асуулт-хариултын урсгал байна.</p></article><article><FlaskConical /><h3>Интерактив лаборатори</h3><p>JavaScript болон Python кодоо браузер дээрээс шууд ажиллуулж, console-ийн үр дүнгээ шалгана.</p></article></div></section>
      <section id="sources" className="home-sources"><p className="section-kicker">ЭХ СУРВАЛЖ</p><div>{courseModules.map((course) => <a key={course.id} href={course.source} target="_blank" rel="noreferrer"><span style={{ color: course.color }}>{course.number}</span><b>{course.label}</b><small>{course.sourceLabel}</small><ChevronRight size={15} /></a>)}</div></section></main>
      <footer className="site-footer"><div className="footer-brand"><img src="/manus-storage/codecraft-atlas-logo_9d75d0e7.png" alt="" /><span><strong>CodeCraft Academy</strong><small>БҮТЭЦТЭЙ СУРАЛЦАХ ОРЧИН</small></span></div><p>HTML · CSS · JavaScript · Python</p></footer>
    </div>
  );
}
