import { ArrowLeft, BookOpenText, ExternalLink, FileText, Smartphone } from "lucide-react";
import { Link, useRoute } from "wouter";
import { courseDocuments } from "@shared/documents";

export default function Library() {
  const [, params] = useRoute("/library/:documentId");
  const selected = courseDocuments.find((item) => item.id === params?.documentId) ?? courseDocuments[0];
  return <div className="min-h-screen bg-[#f7f8fb] text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-10"><Link href="/curriculum" className="flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-950"><ArrowLeft size={16} /> Curriculum</Link><div className="flex items-center gap-2 font-mono text-sm font-bold"><BookOpenText size={17} className="text-violet-600" /> Course library</div></div></header><main className="mx-auto grid max-w-7xl gap-6 px-5 py-8 lg:grid-cols-[300px_1fr] lg:px-10"><aside className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="px-2 pb-3 text-xs font-bold uppercase tracking-[.16em] text-slate-400">Материалууд</p>{courseDocuments.map((document) => <Link key={document.id} href={`/library/${document.id}`} className={`mb-2 block rounded-xl p-3 ${document.id === selected?.id ? "bg-violet-50 text-violet-900" : "hover:bg-slate-50"}`}><div className="flex gap-2"><FileText size={17} className="mt-0.5 shrink-0 text-violet-600" /><div><p className="text-sm font-bold">{document.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{document.pages ? `${document.pages} хуудас · ` : ""}{document.courseId.toUpperCase()}</p></div></div></Link>)}</aside>{selected ? <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 p-5"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-600">{selected.kind}</p><h1 className="mt-1 text-xl font-bold">{selected.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{selected.description}</p></div><a href={selected.href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-slate-950 px-3 py-2 text-xs font-bold text-white hover:bg-violet-700">Шинэ tab-д нээх <ExternalLink size={14} /></a></div><div className="lg:hidden p-6"><div className="rounded-2xl bg-slate-950 p-5 text-white"><Smartphone size={20} className="text-violet-300" /><h2 className="mt-3 text-lg font-bold">Утсаар PDF унших</h2><p className="mt-2 text-sm leading-6 text-white/70">Таны browser embedded PDF viewer-ийг inline харуулахгүй байж болно. Доорх товчоор материалыг шинэ tab-д нээж, native PDF viewer-ээр тасралтгүй уншина.</p><a href={selected.href} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-xs font-bold text-slate-950">PDF нээх <ExternalLink size={14} /></a></div></div><iframe title={selected.title} src={selected.href} className="hidden h-[75vh] min-h-[560px] w-full bg-slate-100 lg:block" /></section> : <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">Одоогоор материал алга.</section>}</main></div>;
}
