import { Button } from "@/components/ui/button";
import { resetPortfolioChecklist, togglePortfolioChecklistItem, type LocalLearningState } from "@/lib/localLearning";
import { CheckCircle2, ExternalLink, Github, RotateCcw } from "lucide-react";
import React from "react";
import "./free-learning.css";

const items = [
  { id: "profile-readme", label: "Profile README repository", detail: "GitHub username-тэй ижил нэртэй public repository, root README.md үүсгэ.", href: "https://docs.github.com/en/account-and-profile/how-tos/profile-customization/managing-your-profile-readme" },
  { id: "profile-story", label: "Өөрийгөө товч танилцуул", detail: "Profile README-д өөрийн зорилго, сурч буй технологи, холбоосоо ойлгомжтой бич.", href: "https://docs.github.com/en/account-and-profile/how-tos/profile-customization/managing-your-profile-readme" },
  { id: "showcase-project", label: "Нэг дууссан project", detail: "HTML/CSS/JavaScript эсвэл Python ашигласан ажиллах project-оо public repository болго.", href: "https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes" },
  { id: "project-readme", label: "Project README", detail: "Юу хийдэг, яагаад хэрэгтэй, хэрхэн эхлэх, тусламж хаанаас авахыг README-д тайлбарла.", href: "https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes" },
  { id: "small-commits", label: "Тодорхой commit history", detail: "Нэг зорилготой жижиг commit, утгатай commit message ашигла.", href: "https://docs.github.com/en/get-started/using-github/github-flow" },
  { id: "feature-branch", label: "Feature branch ба pull request", detail: "Шинэ өөрчлөлтөө тусдаа branch дээр хийгээд pull request нээж review урсгалаар нэгтгэ.", href: "https://docs.github.com/en/get-started/using-github/github-flow" },
  { id: "pin-work", label: "Шилдэг ажлаа profile дээр pin хий", detail: "Хамгийн сайн repository эсвэл gist-ээ сонгож profile дээрээ байрлуул.", href: "https://docs.github.com/en/account-and-profile/how-tos/profile-customization/pinning-items-to-your-profile" },
  { id: "final-review", label: "Шалгаж, холбоосоо турш", detail: "Profile-оо incognito window-д нээж README, project link, live demo ажиллаж байгааг шалга.", href: "https://docs.github.com/en/account-and-profile/how-tos/profile-customization/pinning-items-to-your-profile" },
];

export function GitHubPortfolioChecklist({ learningState, onStateChange }: { learningState: LocalLearningState; onStateChange: (state: LocalLearningState) => void }) {
  const completed = learningState.portfolioChecklistIds.length;
  return <section className="portfolio-checklist" aria-labelledby="portfolio-heading"><div className="portfolio-heading"><div><p className="section-kicker">GITHUB PORTFOLIO</p><h2 id="portfolio-heading">Ажлаа харагддаг болгох checklist.</h2><p>Энэ жагсаалт account-той холбогдохгүй. Алхам бүрийг өөрийн GitHub profile дээр гүйцэтгээд энд тэмдэглэнэ.</p></div><div className="portfolio-count"><Github size={20} /><b>{completed} / {items.length}</b><span>бэлэн</span></div></div><div className="portfolio-progress"><i style={{ width: `${(completed / items.length) * 100}%` }} /></div><div className="portfolio-items">{items.map((item, index) => { const checked = learningState.portfolioChecklistIds.includes(item.id); return <label key={item.id} className={checked ? "portfolio-item checked" : "portfolio-item"}><input type="checkbox" checked={checked} onChange={() => onStateChange(togglePortfolioChecklistItem(item.id))} /><span className="portfolio-tick">{checked ? <CheckCircle2 size={17} /> : String(index + 1).padStart(2, "0")}</span><span><b>{item.label}</b><small>{item.detail}</small></span><a href={item.href} target="_blank" rel="noreferrer" aria-label={`${item.label} албан эх сурвалж`} onClick={(event) => event.stopPropagation()}><ExternalLink size={15} /></a></label>; })}</div><div className="portfolio-footer"><p>Checklist completion: <b>{completed === items.length ? "Portfolio бэлэн боллоо." : `${items.length - completed} алхам үлдлээ.`}</b></p><Button variant="outline" onClick={() => onStateChange(resetPortfolioChecklist())}><RotateCcw size={15} /> Checklist цэвэрлэх</Button></div></section>;
}
