"""Beginner-level Mongolian content for every lesson across the four courses.

Each entry provides tags, keywords, explanation, exercise, and project text.
The build script merges this with the lesson titles/outcomes/tasks extracted
from app.js and emits one file per course and one file per lesson.
"""

CONTENT = {
    "python": {
        "py-start": {
            "tags": ["python", "програм", "интерпретатор", "print"],
            "keywords": ["Python", "program", "interpreter", "print()", "script", "source code"],
            "explanation": "Python бол хүнд ойлгомжтой, эхлэгчдэд хамгийн тохиромжтой програмчлалын хэл юм. Кодыг 'интерпретатор' нэртэй программ мөрөөр мөр уншиж шууд гүйцэтгэдэг. print() функц дэлгэцэнд текст эсвэл утга хэвлэнэ.",
            "exercise": "print() ашиглан өөрийн нэр, нас, дуртай хоббигоо гурван мөрөөр хэвлэ.",
            "project": "Мини төсөл: 'Хувийн танилцуулга' гэсэн 5 мөрт программ бичээд нэр, мэргэжил, хоббигоо хэвлүүл.",
        },
        "py-values": {
            "tags": ["python", "хувьсагч", "төрөл", "string", "integer", "boolean"],
            "keywords": ["variable", "assignment", "string", "integer", "float", "boolean", "type"],
            "explanation": "Хувьсагч нь өгөгдлийг нэрлээд санаж байх сав юм. Python-д төрөл зааж өгөх шаардлагагүй — утга өгөхөд төрөл автоматаар тодорхойлогдоно. String (текст), integer (бүхэл тоо), float (бутархай), boolean (үнэн/худал) гэсэн үндсэн төрлүүд байдаг.",
            "exercise": "Нэр, нас, өндөр, сурдаг эсэх гэсэн 4 хувьсагч үүсгэж, төрөл бүрийн утга өг.",
            "project": "Мини төсөл: Хувьсагч ашиглан зочилсон улсуудын жагсаалтыг хадгалж, тоог нь тооцоол.",
        },
        "py-input": {
            "tags": ["python", "input", "output", "type conversion"],
            "keywords": ["input()", "print()", "int()", "type conversion", "orolt", "garalt"],
            "explanation": "input() нь хэрэглэгчээс текст уншина; үргэлж string буцаадаг. Тоогоор бодохын тулд int() эсвэл float()-оор хөрвүүлэх хэрэгтэй. f-string ашиглан хувьсагчийн утгыг текстийн дотор шууд оруулж болно.",
            "exercise": "Насыг асуугаад дараа жилийн насыг тооцоолж хэвлэ.",
            "project": "Мини төсөл: Хоёр тоог асуугаад нэмэх, хасах, үржүүлэх, хуваах үр дүнг харуулдаг 'Тооны машин' хий.",
        },
        "py-if": {
            "tags": ["python", "нөхцөл", "if", "else"],
            "keywords": ["if", "elif", "else", "condition", "comparison", "boolean"],
            "explanation": "if, elif, else нь кодыг нөхцлөөр шийдвэрлүүлнэ. Нөхцөл нь True эсвэл False утга буцаана; зөвхөн нөхцөл үнэн үед доторх кодын блок ажиллана. Блокуудыг догол (indentation)-оор ялгадаг нь Python-ийн чухал дүрэм.",
            "exercise": "Оноо (0–100) өгөхөд A, B, C, D, F үсгэн үнэлгээг буцаах if/elif/else бич.",
            "project": "Мини төсөл: Температур асуугаад 'халуун', 'дулаан', 'хүйтэн' гэж ангилдаг программ бич.",
        },
        "py-loop": {
            "tags": ["python", "давталт", "for", "while"],
            "keywords": ["for loop", "while loop", "range()", "iteration", "break", "continue"],
            "explanation": "for нь жагсаалт эсвэл range()-ийн элементүүдийг дараалан ажиллуулна. while нь нөхцөл үнэн байхад давтагдана. Давталт нь давтагдах ажлыг богино, алдаагүй бичих арга бөгөөд break давталтыг зогсооно.",
            "exercise": "for давталт ашиглан 1–100 хоорондын тэгш тоонуудын нийлбэрийг ол.",
            "project": "Мини төсөл: Хэрэглэгч зөв тоог таах хүртэл асуудаг 'Тоо таадаг' тоглоом while-оор бич.",
        },
        "py-debug": {
            "tags": ["python", "алдаа", "debug", "синтакс"],
            "keywords": ["SyntaxError", "NameError", "TypeError", "debugging", "traceback"],
            "explanation": "Алдааг гурван төрөлд ялгадаг: SyntaxError (хэлний дүрэм зөрчсөн), RuntimeError (ажиллах үед гарах), LogicError (код ажиллана, гэвч үр дүн буруу). Алдааны traceback-ийн хамгийн сүүлчийн мөр шалтгааныг заана.",
            "exercise": "Өгөгдсөн 3 алдаатай кодны алдааг олж, зөв үр дүн гартал зас.",
            "project": "Мини төсөл: Өөрийн бичсэн кодыг traceback уншиж, алдааны төрөл бүрийг тэмдэглэсэн 'Алдааны журнал' хөтөл.",
        },
        "py-list": {
            "tags": ["python", "list", "жагсаалт", "index"],
            "keywords": ["list", "index", "append()", "len()", "slicing", "sort()"],
            "explanation": "List нь олон утгыг дарааллаар хадгалдаг collection юм. Элементүүд 0-ээс эхлэн index-ээр ханддаг. append() шинэ утга нэмнэ, len() уртыг буцаана, sorted()/sort() эрэмбэлнэ.",
            "exercise": "5 хичээлийн оноог list-д хадгалаад дундаж болон хамгийн өндөр оноог ол.",
            "project": "Мини төсөл: Долоо хоногийн зарцуулалтыг list-д хадгалж, нийт ба дундажийг тооцоолох программ бич.",
        },
        "py-dict": {
            "tags": ["python", "dictionary", "key", "value"],
            "keywords": ["dict", "key-value", "get()", "keys()", "values()", "items()"],
            "explanation": "Dictionary нь key → value хосоор өгөгдлийг хадгална. Хүснэгт/профиль шиг бүтэцэд тохиромжтой. Оноог key-ээр нь ханддаг: profile['name']. get() нь key байхгүй үед төгсгөлгүй утга буцаана.",
            "exercise": "Сурагчийн profile dictionary үүсгээд нэр, нас, хот, дуртай хичээлээ оруул.",
            "project": "Мини төсөл: Хичээл бүрт өгсөн оноог dictionary-д хадгалж, дундаж үнэлгээ тооцоол.",
        },
        "py-function": {
            "tags": ["python", "function", "параметр", "return"],
            "keywords": ["def", "function", "parameter", "argument", "return", "scope"],
            "explanation": "Function нь кодын хэсгийг нэрлээд дахин ашиглах боломж олгоно. def түлхүүр үгээр зарлана; параметрээр оролт авч, return-ээр үр дүн буцаана. Кодыг уншигдахуйц, багассан болгоно.",
            "exercise": "Үнэ болон хөнгөлөлтийн хувь өгөхөд эцсийн үнийг буцаах function бич.",
            "project": "Мини төсөл: Нэмэх, хасах, үржүүлэх, хуваах гэсэн 4 function бүхий 'Тооны машин' нэгтгэ.",
        },
        "py-files": {
            "tags": ["python", "файл", "унших", "бичих"],
            "keywords": ["open()", "read()", "write()", "with", "file", "path"],
            "explanation": "open() функцээр файл нээж, read()/write()-оор унших/бичих боломжтой. 'w' горим файлыг шинээр бичнэ, 'a' горим нэмнэ, 'r' горим уншина. with блок ашиглавал файл автоматаар хаагдана.",
            "exercise": "Тэмдэглэлийн программ бичиж, тэмдэглэлээ файлд хадгалж, дараа уншиж харуул.",
            "project": "Мини төсөл: Файлд тэмдэглэл нэмэх, харах, устгах 'Тэмдэглэл' программ бүтээ.",
        },
        "py-project": {
            "tags": ["python", "төсөл", "cli", "тэмдэглэл"],
            "keywords": ["project", "CLI", "list", "while", "menu", "CRUD"],
            "explanation": "Бүх ойлголтоо нэгтгэж, жинхэнэ CLI бүтээгдэхүүн бүтээнэ. Цэстэй меню, input()-оор командаа аваад, жагсаалт/dictionary ашиглан үйлдэл хийнэ. Ийм жижиг төсөл нь логик ба бүтцийг бэхжүүлнэ.",
            "exercise": "Нэмэх, харах, дуусгах, гарах гэсэн 4 үйлдэлтэй Task tracker CLI бүтээ.",
            "project": "Төсөл: Task tracker-ийг файлд хадгалах хувилбар хүртэл өргөжүүлж, програмыг дахин ажиллуулахад даалгаврууд үлдэнэ.",
        },
        "py-review": {
            "tags": ["python", "шалгалт", "рефактор", "код"],
            "keywords": ["refactor", "review", "edge case", "readability", "testing"],
            "explanation": "Кодыг шалгаж, уншигдахуйц болгох нь мэргэжлийн урсгал. Function-уудыг жижиглэх, нэр утгатай болгох, edge case (хоосон жагсаалт, буруу оролт) шалгах зэрэг орно. Энэ нь тест болон бусад хөгжүүлэгчид ажиллахад бэлтгэнэ.",
            "exercise": "Төслөө function-уудаар хувааж, edge case бүрийг шалга.",
            "project": "Төсөл: Task tracker-ийн кодыг нэр, бүтэц, алдааны удирдлагаар сайжруулж 'v2' хувилбар гарга.",
        },
    },
    "html": {
        "html-web": {
            "tags": ["html", "вэб", "browser", "url"],
            "keywords": ["browser", "server", "URL", "HTTP request", "DNS", "web"],
            "explanation": "Вэб хэрхэн ажилладаг: хөтөч URL руу хүсэлт (request) илгээж, сервер хариу (response) буцаана. HTML нь энэ хариуны агуулга бөгөөд хөтөч түүнийг дэлгэцэнд зурдаг. Request-ийн урсгалыг ойлгох нь веб хөгжүүлэлтийн суурь юм.",
            "exercise": "Нэг web request-ийн урсгалыг: хэрэглэгч → хөтөч → сервер → хариу гэсэн дарааллаар зур.",
            "project": "Мини төсөл: Өөрийнхөө хамгийн их ашигладаг 3 вэб сайтын URL-ийн бүтцийг задлан шинжил.",
        },
        "html-doc": {
            "tags": ["html", "doctype", "head", "body", "meta"],
            "keywords": ["doctype", "html", "head", "body", "meta", "charset", "title"],
            "explanation": "HTML документ нь !DOCTYPE, html, head, body гэсэн стандарт бүтэцтэй. head хэсэгт meta өгөгдөл (charset, description, title) байрлана, body хэсэгт харагдах агуулга орно. Зөв бүтэц нь хөтөч, хайлтын систем зөв ойлгох нөхцөл.",
            "exercise": "Стандарт хангасан, charset болон title бүхий HTML page үүсгэ.",
            "project": "Мини төсөл: 'Миний анхны вэб хуудас' гэсэн, зөв бүтэцтэй page-ээ байгуул.",
        },
        "html-text": {
            "tags": ["html", "текст", "холбоос", "heading", "list"],
            "keywords": ["h1-h6", "p", "a", "ul", "ol", "li", "href", "anchor"],
            "explanation": "Heading (h1–h6) нь бүтцийн шатлал, p нь догол мөр, a нь холбоос, ul/ol + li нь жагсаалт үүсгэнэ. Семантик heading ашиглах нь хайлтын систем болон screen reader-т чухал.",
            "exercise": "Heading, paragraph, list, холбоос бүхий хувийн танилцуулгын page хий.",
            "project": "Мини төсөл: Дуртай 3 зүйлээ холбоос-той жагсаалтаар харуулсан хуудас бүтээ.",
        },
        "html-semantic": {
            "tags": ["html", "semantic", "header", "main", "footer"],
            "keywords": ["header", "nav", "main", "section", "article", "footer", "landmark"],
            "explanation": "Semantic элемент (header, nav, main, section, article, footer) нь хуудасны утгыг хөтөч, screen reader-т тодорхой заана. 'div' нь утгагүй сав боловч semantic элемент нь хүртээмж, SEO-г сайжруулна.",
            "exercise": "Зөвхөн div ашигласан page-ээ semantic элементүүдээр солиж бүтэцлэ.",
            "project": "Мини төсөл: Blog нийтлэлийн хуудасны бүтцийг header/nav/main/article/footer-оор зур.",
        },
        "html-media": {
            "tags": ["html", "зураг", "media", "figure", "alt"],
            "keywords": ["img", "src", "alt", "figure", "figcaption", "picture", "video"],
            "explanation": "img нь зураг харуулна; alt текст зураг ачаалагдахгүй үед эсвэл screen reader-т утга өгнө. figure + figcaption нь зургийн тайлбарыг семантик холбоно. srcset-ээр гүйцэтгэлийг сайжруулж болно.",
            "exercise": "Тайлбартай (alt) 3 зураг бүхий gallery, figure ашиглан хий.",
            "project": "Мини төсөл: Дуртай газруудын gallery-г дахин хэмжээтэй зурагтай бүтээ.",
        },
        "html-table": {
            "tags": ["html", "table", "хүснэгт", "caption"],
            "keywords": ["table", "thead", "tbody", "th", "td", "caption", "scope"],
            "explanation": "Table нь хүснэгтэн өгөгдлийг зөвхөн харуулах — layout-д ашиглахгүй. thead/tbody/tr/th/td бүтцээр зохион байгуулна. caption болон scope нь хүснэгтийг screen reader-т ойлгомжтой болгоно.",
            "exercise": "7 хоногийн хичээлийн хуваарийг caption, scope бүхий table-д хий.",
            "project": "Мини төсөл: Дүнгээ хадгалж, найруулсан хүснэгт бүхий хуудас бүтээ.",
        },
        "html-form": {
            "tags": ["html", "form", "input", "textarea", "button"],
            "keywords": ["form", "label", "input", "textarea", "select", "button", "name"],
            "explanation": "Form нь хэрэглэгчийн оролтыг цуглуулна. label нь оролт бүртэй холбогдож хүртээмжийг хангана. input-ийн type нь өгөгдлийн төрлийг тодорхойлно; name нь серверт илгээх гол түлхүүр юм.",
            "exercise": "Нэр, email, message бүхий бүртгэлийн form үүсгэж, label-аар холбо.",
            "project": "Мини төсөл: Танилцуулгын page-дээ санал авах contact form нэм.",
        },
        "html-validation": {
            "tags": ["html", "validation", "required", "input"],
            "keywords": ["required", "type", "min", "max", "pattern", "placeholder", "constraint"],
            "explanation": "HTML-ийн дотоод validation нь буруу оролтыг сервер рүү явуулахаас өмнө шалгана. required заавал бөглөнө, type=\"email\"/\"number\" төрөл шалгана, min/max хязгаарлана. Амжилттай гэхэд хэрэглэгчид ойлгомжтой feedback үзүүлэх хэрэгтэй.",
            "exercise": "Input type, required, min/max ашиглан алдааны төлөвүүдийг шалга.",
            "project": "Мини төсөл: Насны хязгаар, email форматтай бүртгэлийн форм-оо validation-тай болго.",
        },
        "html-a11y": {
            "tags": ["html", "accessibility", "keyboard", "screen reader"],
            "keywords": ["accessibility", "keyboard", "tab", "aria", "focus", "semantic"],
            "explanation": "Accessibility нь хүн бүр хэрэглэх боломжийг хангана. Keyboard-оор бүх үйлдэл хийгдэх, focus харагдах, aria-attr тодорхой байх, өнгө төдийгөөр утга илэрхийлэхгүй байх зэрэг шаардлагыг шалгана.",
            "exercise": "Mouse-гүйгээр зөвхөн keyboard-оор хуудсаа бүрэн гүйцэтгэж турш.",
            "project": "Мини төсөл: Хуудсаа lighthouse/axe-ээр шалгаж, илэрсэн a11y алдаагаа зас.",
        },
        "html-plan": {
            "tags": ["html", "төлөвлөлт", "wireframe", "outline"],
            "keywords": ["wireframe", "outline", "content", "heading map", "planning"],
            "explanation": "Код бичихээс өмнө контентоо төлөвлөнө. Wireframe нь хуудасны бүтцийн ноорог, heading map нь гарчгийн шатлал юм. Төлөвлөгөө нь тодорхой, хэрэглэгч төвтэй хуудас бүтээхэд тусална.",
            "exercise": "Landing page-ийнхаа heading map (h1–h3) гарга.",
            "project": "Мини төсөл: Portfolio-ийн бүх section-ийн wireframe болон heading map зур.",
        },
        "html-build": {
            "tags": ["html", "portfolio", "төсөл", "hero"],
            "keywords": ["portfolio", "hero", "work", "about", "contact", "project"],
            "explanation": "Бодит portfolio бүтээнэ: Hero (танилцуулга), Work (төслүүд), About (өөрийн тухай), Contact (холбоо барих) гэсэн семантик бүтэцтэй. Энэ бол ажил олгогчид үзүүлэх анхны бодит бүтээгдэхүүн.",
            "exercise": "Hero, work, about, contact гэсэн 4 section-той portfolio-оо бүтээ.",
            "project": "Төсөл: Порфолио хуудсаа бүрэн контентоор дүүргэж, семантик, хүртээмжтэй болго.",
        },
        "html-audit": {
            "tags": ["html", "аудит", "semantic", "шалгалт"],
            "keywords": ["audit", "validator", "semantic", "accessibility", "checklist"],
            "explanation": "HTML аудит нь семантик зөв, хүртээмжтэй, validate-д орж байгаа эсэхийг шалгана. W3C validator, heading map, alt текст, keyboard зэргийг дайрна. Аудит төслийг production-д бэлтгэдэг.",
            "exercise": "Checklist ашиглан төслөө семантик ба accessibility-гээр шалга.",
            "project": "Төсөл: Portfolio-оо W3C validator-аар шалгаж, бүх алдааг зас.",
        },
    },
    "css": {
        "css-start": {
            "tags": ["css", "selector", "style"],
            "keywords": ["selector", "class", "id", "element", "declaration", "property"],
            "explanation": "CSS нь HTML-ийн харагдацыг тодорхойлно. Selector нь аль элементийг онилно, declaration нь property: value хосоор стиль өгнө. Class (.) нь дахин ашиглагдах, id (#) нь өвөрмөц элементийг онилно.",
            "exercise": "Profile card-ын selector-уудыг (class, id, element) бичиж стиль өг.",
            "project": "Мини төсөл: Нэг элементийг 3 өөр selector-оор онилж, давуу талыг харьцуул.",
        },
        "css-cascade": {
            "tags": ["css", "cascade", "specificity"],
            "keywords": ["cascade", "specificity", "inheritance", "order", "importance"],
            "explanation": "Cascade нь хэдэн стиль давхцвал алийг нь хэрэглэхийг шийднэ: specificity (id > class > element), эрэмбэ (сүүлийнх ялна), important. Яагаад стиль үйлчилж байгааг тайлбарлах чадвар нь алдаа багасгана.",
            "exercise": "Зөрчилтэй declaration-уудыг specificity дээр үндэслэн цэгцэл.",
            "project": "Мини төсөл: 3 давхар зөрчилтэй стиль гаргаж, ямар дүрэм ялсныг тайлбарла.",
        },
        "css-box": {
            "tags": ["css", "box model", "padding", "margin"],
            "keywords": ["content", "padding", "border", "margin", "box-sizing", "width"],
            "explanation": "Бүх элемент нь box: content + padding + border + margin. Padding дотор зай, margin гадна зай, border хүрээ. box-sizing: border-box ашиглавал нийт өргөнийг тооцоолоход хялбар болно.",
            "exercise": "Card-ын padding, border, margin-ийг тооцоолж spacing тааруул.",
            "project": "Мини төсөл: Box-sizing ашигласан, зөв spacing-тай card component бүтээ.",
        },
        "css-flex": {
            "tags": ["css", "flexbox", "layout", "navbar"],
            "keywords": ["display:flex", "justify-content", "align-items", "flex-wrap", "gap"],
            "explanation": "Flexbox нь нэг хэмжээст layout-ийг хялбар болгоно. display:flex-ээр эхэлж, justify-content (хэвтээ), align-items (босоо) тохируулна. Navbar, товч багц, зэрэгцүүлэлтэд тохиромжтой.",
            "exercise": "Responsive navbar-ыг flex ашиглан хий.",
            "project": "Мини төсөл: Товч багц, зэрэгцүүлсэн feature блокуудыг flex-ээр бүтээ.",
        },
        "css-grid": {
            "tags": ["css", "grid", "layout", "dashboard"],
            "keywords": ["display:grid", "grid-template-columns", "grid-template-rows", "gap", "auto-fit"],
            "explanation": "CSS Grid нь хоёр хэмжээст (мөр, багана) layout үүсгэнэ. grid-template-columns-оор багануудыг тодорхойлно. Dashboard, gallery, картын сүлжээнд Flexbox-оос хүчтэй.",
            "exercise": "Dashboard grid-ийг grid-template-columns ашиглан бүтээ.",
            "project": "Мини төсөл: auto-fit/minmax ашигласан responsive картын сүлжээ хий.",
        },
        "css-position": {
            "tags": ["css", "position", "sticky", "z-index"],
            "keywords": ["relative", "absolute", "fixed", "sticky", "z-index", "top/left"],
            "explanation": "position нь элементийг байршуулна: relative (өөрийн байрлалаас), absolute (эцэгээс), fixed (дэлгэцээс), sticky (скролл үед наалдана). z-index нь давхцсан элементүүдийн дарааллыг шийднэ.",
            "exercise": "Sticky header хийж, z-index-ээр давхцлыг удирд.",
            "project": "Мини төсөл: Sticky navbar + модал window (overlay) бүхий хуудас хий.",
        },
        "css-responsive": {
            "tags": ["css", "responsive", "mobile", "media query"],
            "keywords": ["media query", "viewport", "breakpoint", "mobile-first", "min-width"],
            "explanation": "Responsive гэдэг нь бүх дэлгэцэнд тохирох явдал. Mobile-first аргаар эхлээд жижиг дэлгэцэд зохиож, media query (min-width)-аар томд нь нэмнэ. Breakpoint-ийг контентоосоо хамааруулж сонгоно.",
            "exercise": "Portfolio-г 3 дэлгэцийн хэмжээнд (mobile, tablet, desktop) тохируул.",
            "project": "Мини төсөл: Өөрийн page-ийг 320–1440px хүртэл responsive болго.",
        },
        "css-fluid": {
            "tags": ["css", "fluid", "clamp", "unit"],
            "keywords": ["clamp()", "minmax()", "vw", "em", "rem", "relative unit"],
            "explanation": "Fluid типографи өгөгдсөн хязгаар дотор дэлгэцийн хэмжээгээр автомат өөрчлөгдөнө. clamp(min, val, max) нь гурван үе шаттай хэмжээ, minmax() нь grid-д хамгийн бага/ихыг тодорхойлно. rem-ээр font-ыг төвлөрүүлнэ.",
            "exercise": "Heading ба grid-ээ clamp(), minmax() ашиглан fluid болго.",
            "project": "Мини төсөл: Бүх heading-ээ clamp() ашигласан fluid type систем болго.",
        },
        "css-query": {
            "tags": ["css", "container query", "component"],
            "keywords": ["container-type", "container queries", "@container", "size query"],
            "explanation": "Container query нь компонентийг дэлгэц биш, өөрийн контейнерийн хэмжээгээр тохируулна. @container-ээр карт өөр контейнерт өөр стиль авна. Энэ нь component-д суурилсан responsive-ийн шинэ арга.",
            "exercise": "Контейнерийнхээ хэмжээнд дасан зохицох responsive card хий.",
            "project": "Мини төсөл: Хоёр өөр хэмжээтэй контейнерт нэг карт компонент туршиж үз.",
        },
        "css-token": {
            "tags": ["css", "design token", "variable", "theme"],
            "keywords": ["custom property", "CSS variable", ":root", "color", "spacing", "type scale"],
            "explanation": "Design token нь өнгө, spacing, type зэрэг дизайны шийдвэрийг CSS variable болгон нэгтгэнэ. --brand гэх мэт variable-ийг :root дээр зарлаж, дахин ашиглана. Токен систем нь солиход хялбар, тогтвортой UI өгнө.",
            "exercise": "Өнгө, spacing, type-ээ CSS variable болгон токен set үүсгэ.",
            "project": "Мини төсөл: Токенуудаа dark/light theme-ээр сольж харуулах жижиг систем хий.",
        },
        "css-component": {
            "tags": ["css", "component", "button", "variant"],
            "keywords": ["variant", "state", "hover", "focus", "disabled", "BEM"],
            "explanation": "Компонент нь variant (primary/secondary), size (sm/md/lg), state (hover/focus/disabled)-ээр загварчлагдана. Ингэснээр кодын давталт багасч, UI тогтвортой болно. Нэрийн систем (BEM гэх мэт) ашиглавал уншигдахуйц болно.",
            "exercise": "Button-ийн 3 variant ба state-ийг загварчил.",
            "project": "Мини төсөл: 5 үндсэн компонент (button, input, card, tag, badge)-оос бүрдсэн жижиг UI kit хий.",
        },
        "css-motion": {
            "tags": ["css", "animation", "transition", "motion"],
            "keywords": ["transition", "animation", "@keyframes", "transform", "reduced-motion"],
            "explanation": "Motion нь UI-г амьдралтай болгоно. transition нь төлөв өөрчлөгдөхөд зөөлөн шилжинэ, @keyframes нь төвөгтэй animation хийх боломж олгоно. Хэт олон анимейшн хэрэглэгчийг сатааруулна; reduced-motion-д хүндэтгэх хэрэгтэй.",
            "exercise": "Transition, @keyframes ашиглан зорилготой animation хий.",
            "project": "Мини төсөл: prefers-reduced-motion-ыг хүндэтгэсэн, зөөлөн анимейшн бүхий компонент хий.",
        },
        "css-figma": {
            "tags": ["css", "дизайн", "mockup", "код"],
            "keywords": ["mockup", "spacing", "type scale", "color", "measure", "design to code"],
            "explanation": "Дизайнаас код руу: mockup-ын spacing, type, color-ийг хэмжиж, токенуудтай холбоно. Энэ урсгал дизайнер ба хөгжүүлэгчийн ажлыг холбоно. Үнэн зөв хэмжилт нь дизайнтай таарсан UI өгнө.",
            "exercise": "Mockup hero-г хэмжиж, токенуудаараа кодло.",
            "project": "Мини төсөл: Өөрийн сонгосон landing mockup-ыг бүрэн кодлож, дизайнтай нь жиш.",
        },
        "css-project": {
            "tags": ["css", "төсөл", "saas", "landing"],
            "keywords": ["production", "landing page", "nav", "pricing", "responsive", "section"],
            "explanation": "Бодит production responsive page бүтээнэ: nav, hero, feature, pricing, footer гэх мэт 6+ section. Токен, grid, flex, responsive бүгдийг нэгтгэнэ. Энэ нь portfolio-д орох гол бүтээл байж болно.",
            "exercise": "6 section, nav, pricing бүхий SaaS landing page бүтээ.",
            "project": "Төсөл: Landing page-ээ 320–1440px хүртэл responsive, анимацитай болго.",
        },
        "css-audit": {
            "tags": ["css", "аудит", "visual qa", "qa"],
            "keywords": ["overflow", "contrast", "edge case", "validation", "performance"],
            "explanation": "Visual QA нь overflow, contrast, hover/focus state, зөв буруу нөхцлийг шалгана. Contrast хангалттай (WCAG), жижиг дэлгэцэд overflow гарахгүй, бүх state ажиллаж байгаа эсэхийг баталгаажуулна.",
            "exercise": "Төслөө 320–1440px хүртэл шалгаж, overflow ба contrast алдааг зас.",
            "project": "Төсөл: Landing page-ээ бүрэн аудит хийж, бүх илэрсэн алдааг засч v2 гарга.",
        },
    },
    "javascript": {
        "js-values": {
            "tags": ["javascript", "хувьсагч", "const", "let"],
            "keywords": ["const", "let", "var", "primitive", "number", "string", "boolean"],
            "explanation": "JavaScript-д хувьсагчийг const (өөрчлөгдөхгүй) болон let (өөрчлөгддөг) гэж зарлана. Primitive төрлүүд: number, string, boolean, null, undefined, symbol. Төрөл динамик бөгөөд хадгалагдсан утгаар тодорхойлогдоно.",
            "exercise": "Сагсны барааны нэр, үнэ, тоо хэмжээг хувьсагчид хадгалж нийт үнэ бод.",
            "project": "Мини төсөл: const/let зөв ашигласан 'Сагс' тооцооллын жижиг скрипт бич.",
        },
        "js-logic": {
            "tags": ["javascript", "нөхцөл", "loop", "control flow"],
            "keywords": ["if", "else", "switch", "for", "while", "comparison", "logical operator"],
            "explanation": "Control flow нь програмын гүйлтийг шийдвэрлүүлнэ. if/else нь нөхцөлөөр, for/while нь давталтаар ажиллана. === нь төрөл ба утгыг чанга шалгана, логик операторууд (&&, ||) нь нөхцөлийг нэгтгэнэ.",
            "exercise": "Password strength-ийг урт, цифр, тэмдэгтээр нь шалгадаг функц бич.",
            "project": "Мини төсөл: Оноо → үсгэн үнэлгээ хөрвүүлдэг шалгалтын скрипт хий.",
        },
        "js-function": {
            "tags": ["javascript", "function", "arrow"],
            "keywords": ["function", "arrow function", "parameter", "return", "default param"],
            "explanation": "Function нь оролт (input) аваад үр дүн (output) буцаана. function болон arrow (=>) гэсэн хоёр хэлбэртэй. Параметр нь оролт, return нь гарц. Кодыг логикоор бүлэглэж, дахин ашиглах боломж олгоно.",
            "exercise": "Үнийг format хийж (₮ 1,250) буцаах formatPrice() функц бич.",
            "project": "Мини төсөл: 5 utility функц (бодох, format, validate) бүхий жижиг module хий.",
        },
        "js-array": {
            "tags": ["javascript", "array", "map", "filter", "reduce"],
            "keywords": ["map", "filter", "find", "reduce", "forEach", "spread", "destructure"],
            "explanation": "Array method нь collection-ыг функциональ аргаар боловсруулна: map (хувиргах), filter (шүүх), find (олох), reduce (хураах). Тэдгээр нь шинэ array буцааж, анхны өгөгдлийг өөрчлөхгүй.",
            "exercise": "Product list-ээ үнэ, категориар шүүж, map/filter ашиглан үзүүл.",
            "project": "Мини төсөл: Төсвийн зарцуулалтыг reduce ашиглан дүнлэдэг скрипт бич.",
        },
        "js-object": {
            "tags": ["javascript", "object", "data"],
            "keywords": ["object", "property", "method", "this", "JSON", "spread"],
            "explanation": "Object нь key → value хосоор өгөгдлийг загварчилна. Курс, хэрэглэгч гэх мэт бодит зүйлийг төлөөлөхөд тохиромжтой. Property, method (функц), spread (...) нэгтгэх зэрэг үйлдэлтэй.",
            "exercise": "Course card-ын өгөгдлийг object болгон загварчилж render хий.",
            "project": "Мини төсөл: Object array-г үзүүлж, шинэ зүйл нэмэх/хасах жижиг UI хий.",
        },
        "js-module": {
            "tags": ["javascript", "module", "import", "export"],
            "keywords": ["import", "export", "ES module", "default export", "named export"],
            "explanation": "Module нь кодыг файл болгон хувааж, хариуцлагыг салгана. export-аар илгээж, import-аар хүлээн авна. Ингэснээр код уншигдахуйц, тест хийхэд хялбар болно.",
            "exercise": "Utility ба UI функцуудыг өөр өөр module болгон хувааж export/import хий.",
            "project": "Мини төсөл: Кодоо 3 module (data, logic, ui) болгон зохион байгуул.",
        },
        "js-dom": {
            "tags": ["javascript", "dom", "render"],
            "keywords": ["DOM", "querySelector", "createElement", "textContent", "innerHTML"],
            "explanation": "DOM нь хуудасны бүтцийг объект болгон хандана. querySelector-ээр элемент олж, textContent/appendChild-аар аюулгүй шинэчилнэ. Хэрэглэгчийн өгөгдлийг innerHTML-д шууд хийхгүй — XSS-ээс сэргийлнэ.",
            "exercise": "Todo item-ийг DOM-ээр аюулгүй render хийж нэм.",
            "project": "Мини төсөл: Жагсаалт render хийдэг, аюулгүй (esc) жижиг UI бүтээ.",
        },
        "js-event": {
            "tags": ["javascript", "event", "delegation"],
            "keywords": ["addEventListener", "event object", "target", "delegation", "propagation"],
            "explanation": "Event нь хэрэглэгчийн үйлдлийг (click, input) код руу хүргэнэ. addEventListener-ээр холбож, event объектоор дэлгэрэнгүй мэдээлэл авна. Delegation нь эцэг дээр нэг listener-оор олон хүүхдийг удирдах арга.",
            "exercise": "Динамик нэмэгдэх delete товчнуудыг event delegation ашиглан холбо.",
            "project": "Мини төсөл: Жагсаалт + нэмэх/устгах, delegation бүхий хялбар app хий.",
        },
        "js-state": {
            "tags": ["javascript", "state", "render", "ui"],
            "keywords": ["state", "single source of truth", "render", "event → state → render"],
            "explanation": "UI state нь өгөгдлийн нэг 'source of truth' байна. Үйлдэл state-ийг өөрчилж, render функц state-аас дэлгэцийг зураад дахин зурна. Энэ загвар нь UI-ийн логикийг ойлгомжтой, алдааг багасгана.",
            "exercise": "Filter-тэй task app-ийг нэг state-аас render хийх загвараар бүтээ.",
            "project": "Мини төсөл: Filter, хайлт, тоолуур бүхий state-т task app хий.",
        },
        "js-form": {
            "tags": ["javascript", "form", "validation"],
            "keywords": ["submit", "preventDefault", "FormData", "error feedback", "validate"],
            "explanation": "Form-ийн submit-ийг зогсоож (preventDefault), өгөгдлийг шалгаад боловсруулна. FormData-аар оролтыг цуглуулна. Алдааг талбар дээр ойлгомжтой харуулж, амжилтын feedback өгнө.",
            "exercise": "Signup form-ийг submit ба error feedback-тэй бүтээ.",
            "project": "Мини төсөл: Email, password, confirm гэсэн 3 талбартай, бүрэн validate хийдэг form хий.",
        },
        "js-async": {
            "tags": ["javascript", "async", "promise", "await"],
            "keywords": ["async/await", "Promise", "fetch", "try/catch", "event loop"],
            "explanation": "Async код нь удаан ажиллагааны хариу хүлээхдээ UI-г бөглөхгүй. async/await нь Promise-ийг шугаман код шиг бичих боломж олгоно. try/catch ашиглан асинхрон failure-ийг удирдана.",
            "exercise": "Хоёр API request-ийг нэгтгэж, алдааг try/catch-аар удирда.",
            "project": "Мини төсөл: Нэг API-аас өгөгдөл татаж, амжилт/алдааны төлөвийг харуул.",
        },
        "js-fetch": {
            "tags": ["javascript", "fetch", "rest api", "json"],
            "keywords": ["fetch", "REST", "GET", "JSON", "response.ok", "status"],
            "explanation": "fetch() нь сүлжээний хүсэлт илгээж Promise буцаана. response.ok ба status-ээр амжилтыг шалгаж, response.json()-оор өгөгдлийг задална. REST API-аас өгөгдөл авч UI-д үзүүлнэ.",
            "exercise": "API-аас card list татаж, loading/error төлөвтэй харуул.",
            "project": "Мини төсөл: Нийтийн API (жишээ нь сагс/хэрэглэгч) ашиглан бодит list app хий.",
        },
        "js-ui": {
            "tags": ["javascript", "ui state", "loading", "error"],
            "keywords": ["loading", "empty", "error", "retry", "skeleton", "status"],
            "explanation": "Асинхрон UI нь loading, empty, error гэсэн бүх төлөвийг харуулах ёстой. Эдгээр төлөв нь хэрэглэгчийн төлөвшилд ойлгомжтой байна. Error үед retry (дахин оролдох) боломж өгнө.",
            "exercise": "API-ийн бүх төлөвийг (loading/empty/error) харуулж, retry flow нэм.",
            "project": "Мини төсөл: Skeleton loader, empty state, retry бүхий бүрэн UI хий.",
        },
        "js-storage": {
            "tags": ["javascript", "localstorage", "persist"],
            "keywords": ["localStorage", "sessionStorage", "JSON.stringify", "JSON.parse", "persist"],
            "explanation": "localStorage нь өгөгдлийг хөтөчид байнгын хадгална. Зөвхөн текст хадгалдаг тул object-ийг JSON.stringify/parse-аар хөрвүүлнэ. Энэ нь app-ийн төлөвийг дахин ачаалласны дараа хадгална.",
            "exercise": "Task app-ийн төлөвийг localStorage-д хадгалж, дахин ачааллахад сэргээ.",
            "project": "Мини төсөл: Persist хийдэг task app-ээ filter-тэй болгон өргөжүүл.",
        },
        "js-architecture": {
            "tags": ["javascript", "architecture", "төлөвлөлт"],
            "keywords": ["architecture", "data flow", "modules", "planning", "capstone"],
            "explanation": "Төслийн архитектур нь өгөгдлийн урсгал, модулийн хуваарилалт, state-ийн зохион байгуулалтыг тодорхойлно. Эхлээд data flow зурж, дараа нь кодлох нь төсвийг багасгана. Capstone төслийн төлөвлөгөө гаргана.",
            "exercise": "Capstone төслийнхөө feature data flow-г зур.",
            "project": "Мини төсөл: Dashboard app-ийн бүрэн төлөвлөгөө (хуудас, state, модуль) бич.",
        },
        "js-project": {
            "tags": ["javascript", "төсөл", "dashboard"],
            "keywords": ["dashboard", "API", "filter", "modal", "MVP"],
            "explanation": "Frontend capstone: API, filter, modal бүхий dashboard app бүтээнэ. MVP-ээ эхлээд, дараа нь өргөжүүлнэ. State, module, async, event бүх ойлголтыг нэг бүтээгдэхүүнд нэгтгэнэ.",
            "exercise": "API, filter, modal бүхий dashboard app-ийн MVP хэрэгжүүл.",
            "project": "Төсөл: Dashboard app-ээ бүрэн ажиллагаатай болгож, өгөгдлийг API-аас татаж, хэрэглэгчийн үйлдлээр filter хий.",
        },
        "js-quality": {
            "tags": ["javascript", "test", "performance", "qa"],
            "keywords": ["devtools", "console", "network", "performance", "smoke test", "debug"],
            "explanation": "Quality нь DevTools-аар алдаа олж, гүйцэтгэл ба ашиглалтыг шалгана. Console, Network, Performance табуудыг ашиглаж, smoke test (гол урсгалын шалгалт)-ээр бүтээгдэхүүний бэлэн байдлыг баталгаажуулна.",
            "exercise": "DevTools-аар консол алдаа, network хариуг шалгаж, smoke test нэм.",
            "project": "Мини төсөл: Dashboard-оо тест хийж, олдсон бүх алдааг засаж v2 гарга.",
        },
        "js-deploy": {
            "tags": ["javascript", "deploy", "portfolio"],
            "keywords": ["deploy", "build", "static hosting", "case study", "portfolio"],
            "explanation": "Deploy нь бүтээгдэхүүнийг олонд хүргэнэ. Static hosting-т байршуулж, production demo бэлдэж, case study бичнэ. Бодит URL бүхий portfolio нь ажилд орох хүсэлтэд хүчтэй нотолгоо болно.",
            "exercise": "Production demo бэлдэж, төслөө deploy хий.",
            "project": "Төсөл: Dashboard-оо deploy хийж, case study нийтэлж, portfolio-доо нэм.",
        },
    },
}